### ISSUE TITLE
Implement ActionHero micro-service with OAuth 2 or OpenID Connect

### ISSUE THREAD

**Issue by TechMaster** [evantahler/actionhero#1002]
![actionhero_openid_oauth2](https://cloud.githubusercontent.com/assets/1491686/22512333/40194d12-e8cb-11e6-8219-17b789dc08a4.jpg)

Hi all,

I am going to build micro-service system. In that some will base on ActionHero, other will base on Express.

I will centralise and delegate user authentication and user service to one microservice. I am going to use OAuth2 or recent OpenID connect. There is one good module, [oauth2orize](https://www.npmjs.com/package/oauth2orize) to implement OAuth2. Development OAtuh protected micro-service with Express is relatively straight forward, since many examples are written for Express.

My question is how to implement similarly for ActionHero based micro-service. What should I care when porting from Express to ActionHero microservice?

Thanks

**Comment by evantahler** [comment]
This is not an issue with ActionHero, nor is it a feature request.  To that end, I'm closing this issue.  Should you want advice on how to use oAuth with actionhero (I agree there don't seem to be any good examples published), please reach out to the community on [Slack](https://slack.actionherojs.com/)
