### ISSUE TITLE
Feature: Add support for namespacing the Redis Resque keys

### ISSUE THREAD

**Issue by vladbalmos** [evantahler/actionhero#1012]
# Add support for namespacing the Redis Resque keys

When running different actionhero nodes using the same Redis host, the tasks of each node overlap with the others and generate errors.

- ActionHero Version: `all`
- Node.js Version: `all`
- Operating System `all`

I have a use case in which different actionhero microservices use the same Redis host to communicate, and each of those nodes have a different tasks that need to be run. The problem is that each node uses the same resque redis key to keep track of the tasks and this causes errors in all the nodes.

To fix this issue I created a an initializer which overrides the default namespace key for resque:

    api.resque.connectionDetails.namespace = api.config.general.resqueScheduler.namespace;

But it would be nice if this could be added to the appropriate task configuration section.

Thanks!

**Comment by evantahler** [comment]
Hi Vlad, that's a good hack.  
To better understand your use-case, can you share why changing the redis DB identifier (0,1,2,etc) is not viable for your use-case?

**Comment by vladbalmos** [comment]
Hi Evan,
Thank you for the reply.I have 3 microservices that share the same data structures in Redis. For example microservice A creates a redis hash with the key X. The microservice B then receives the key X from a client and is responsible with manipulating only some of the fields in the hash X.
If I would to set each microservice use a different redis db, then from my understanding of redis db - the data could not be shared between then - if this is not the case, please correct me and this feature would not be necessary.
Regards,Vlad Balmos 

    On Friday, March 3, 2017 7:18 AM, Evan Tahler <notifications@github.com> wrote:
 

 Hi Vlad, that's a good hack.
To better understand your use-case, can you share why changing the redis DB identifier (0,1,2,etc) is not viable for your use-case?—

**Comment by vladbalmos** [comment]
While explaining my use case to you I had another ideea which would solve this. I could create a new Redis client which would use the same DB as the other  microservice and its primary use case would be to share the common data, and the default actionhero client would use another DB to prevent the conflicts.

I'll be closing this issue. Thanks for helping me discover this new fix :))
