### ISSUE TITLE
Create scripts for all binary commands (generate, generateAction, etc)

### ISSUE THREAD

**Issue by evantahler** [evantahler/actionhero#181]
Once we do this, we can update the install instructions to be `npm run-script actionHero generate` which is a little cleaner

**Comment by jacobfike** [comment]
Things like mocha recommend installing globally to get the cli commands, and also installing locally to control the version used by your project.  It should be possible to detect what directory the executable is in vs. the current working directory and then call the locally installed actionhero generator, passing it the arguments given to the global one.

That would give you the best of both worlds.  All the convenience of system-wide cli commands, but you don't have to worry about version mismatches.

**Comment by evantahler** [comment]
ahh! That`s a good idea.  Please submit a PR!
