### ISSUE TITLE
refactor actionsView/self-documentation into a known format

### ISSUE THREAD

**Issue by evantahler** [evantahler/actionhero#44]
![swagger_screenshot.png](https://f.cloud.github.com/assets/303226/1946/77130ab6-4162-11e2-928d-ac1fdad63be2.png)
Perhaps Swagger?
https://github.com/wordnik/swagger-core/wiki/API-Declaration

**Comment by BoLaMN** [comment]
Ive got the basics of this done with the swagger 2.0 api without the need to change anything i just need to finish up the linking the inputs and custom routes which shouldn't take long.

not sure if its going to be possible todo the custom validators thou as thats kinda out of scope for a normal api solution.

![screen shot 2015-05-13 at 9 47 26 pm](https://cloud.githubusercontent.com/assets/414479/7610181/01f24b6c-f9ba-11e4-9152-50d6f705411e.png)

ill throw a plugin up once its in a state that its actually helpful.

**Comment by evantahler** [comment]
This is awesome!  Are you able to get the route params sorted out as well?  If you are able to do this in one action, I'm OK swapping the format of the documentation to swagger itself (as it's fairly arbitrary as it is now)

**Comment by BoLaMN** [comment]
only started playing with it tonight but i think ive cracked the actions\inputs side of it 

![screen shot 2015-05-13 at 11 33 13 pm](https://cloud.githubusercontent.com/assets/414479/7612237/a9c8c6f0-f9c8-11e4-8d94-a92d597c1769.png)

ill start playing with the route params soon but should be fairly easy as when it maps the actions it generates the parameters and schema definitions so the custom routes should be able to piggy back off the previously mapped definitions

**Comment by BoLaMN** [comment]
Is there any reason we don't allow defining the routes within the actions? Wouldnt it be easier to maintain routes contained to their actions?

**Comment by evantahler** [comment]
Because actions are not only for HTTP transports.

**Comment by BoLaMN** [comment]
You'd still leave the rest the same so the other transports can talk directly to the actions id just extend the loader to iterate over the routes object while it's iterating over the actions building the simple routes

**Comment by BoLaMN** [comment]
i guess i can support it my self through an initialiser anyway
 
eg. https://gist.github.com/BoLaMN/113ef0f29146867bacee

**Comment by evantahler** [comment]
I guess I'd be open to moving routes into the action definition if everyone was onboard (bring it up on the mailing list).  For now though, this PR should work with the "current state of the world"

**Comment by PhilWaldmann** [comment]
:+1:

**Comment by BoLaMN** [comment]
got caught up in a new angular project. I'll try get something up mid next week for review.

Also not sure if we should include the swagger ui as default or just make the endpoint available instead and leave it up to the user to include, thoughts?

**Comment by evantahler** [comment]
I think the goal should be to:
- replace the showDocumentarion action and initializer with the swagger
stuff
- either include the swagger UI in /public or bake it into index.html, eg
cig already shows docs

On Saturday, May 16, 2015, BoLaMN <notifications@github.com> wrote:

> got caught up in a new angular project. I'll try get something up mid next
> week for review.
>
> Also not sure if we should include the swagger ui as default or just make
> the endpoint available instead and leave it up to the user to include,
> thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evantahler/actionhero/issues/44#issuecomment-102589705>
> .
>


-- 
--
 *Evan Tahler* | evantahler@gmail.com | +1 (415) 413-8268
 evantahler.com | actionherojs.com

**Comment by BoLaMN** [comment]
alright im pretty much done with the initializer just need to intergrate the swagger ui into actionhero now then ill create PR for review.
 
![screen shot 2015-05-19 at 9 23 02 am](https://cloud.githubusercontent.com/assets/414479/7692896/c375e634-fe08-11e4-875f-dce79eee0d94.png)

**Comment by evantahler** [comment]
That's awesome!

**Comment by evantahler** [comment]
We have a swagger plugin now https://github.com/supamii/ah-swagger-plugin
