### ISSUE TITLE
We need a better default page theme

### ISSUE THREAD

**Issue by evantahler** [evantahler/actionhero#530]
This is ugly.  We need a better one 

![screen shot 2014-12-28 at 10 09 03 pm](https://cloud.githubusercontent.com/assets/303226/5566477/376c7a84-8ede-11e4-8355-945529172ff1.png)

**Comment by jackbit** [comment]
How can you get Server Name, API Version and Actions list? mine haven't them

**Comment by slattery** [comment]
@jackbit are you looking at a public/index.html from a clean `actionhero generate/npm install/actionhero start'?    (this may deserve its own issue, or check out the email list/gitter chat)

**Comment by evantahler** [comment]
For reference, MASTER is always deployed to demo.actionherojs.com.  This page requires a few actions to be active within the sevrer.

**Comment by evantahler** [comment]
Closing in favor of https://github.com/evantahler/actionhero/pull/551
