### ISSUE TITLE
Greedy Memory Issue

### ISSUE THREAD

**Issue by jackbit** [evantahler/actionhero#540]
I have no idea why ActionHero takes so much memory, here is my result from production server:

````
 ps -eo size,pid,user,command --sort -size | awk '{ hr=$1/1024 ; printf("%13.2f MB ",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }' | grep node
````

````
  670.26 MB /usr/bin/nodejs /home/user/project/current/node_modules/actionhero/bin/actionhero start
  649.17 MB node /home/user/project/current/node_modules/actionhero/bin/actionhero startCluster --workers=1 --isDaemon=true
  0.32 MB grep --color=auto node
````

#### My packages ####

````
  "engines"     : {
    "node": ">=0.10.0"
  },
  "dependencies" : {
    "actionhero" : "9.4.1",
    "ws"         : "0.5.0",
    "grunt"      : "0.4.5",
    "sequelize"  : "2.0.0-rc2",
    "pg"         : "4.0.0",
    "redis"      : "0.12.1",
    "sha1"       : "1.1.0",
    "lodash"     : "2.4.0",
    "humanize"   : "0.0.9",
    "nodemailer" : "1.3.0",
    "pretty-error" : "1.1.1",
    "crypto"     : "0.0.3"
  },
  "devDependencies" : {
    "request" : "2.51.0",
    "mocha"  : "2.0.1",
    "should" : "4.3.0",
    "nodemailer-browser-transport" : "0.0.4",
    "open": "0.0.5"
  },
  "scripts" : {
    "help"         : "actionhero help",
    "start"        : "actionhero start",
    "actionhero"   : "actionhero",
    "startCluster" : "actionhero startCluster",
    "test"         : "mocha",
    "deploy"       : "mina deploy"
  },
````

Total project folder size:

without folders node_modules, .git, log and tmp is 308KB
with folders node_modules, .git, log and tmp is 1.5MB

Any idea? Many thanks

**Comment by evantahler** [comment]
Hi @jackbit.  Saddly, you have a lot of plugins there, so I can't really help you out.  The memory hog could be any number of those plugins and their dependancies... or you just might have a lot of traffic!   Strat playing around with heap-dumps, and you can at least start by counting up the *types* of objects you have which are filling up your ram.  Perhaps you have a ton of un-collected DB model instances (sequelize) or email templates (nodemailer).

I can confirm that a "plain" actionhero server running for a few weeks shouldn't go over ~20mb with "reasonable" load
