### ISSUE TITLE
`_originalConnection` is consufing and complicated.  It makes it hard to modify persistent connection properties.

### ISSUE THREAD

**Issue by evantahler** [evantahler/actionhero#561]
- Do we really need `_originalConnection` in middleware / actions?
- How can we better deal with connection property changes?

**Comment by evantahler** [comment]
This will require an API change to all actions.  Something like:

```javascript
exports.randomNumber = {
  name: 'randomNumber',
  description: 'I am an API method which will generate a random number',
  outputExample: {
    randomNumber: 0.123
  },
  
  run: function(api, connection, params, response, next){
    response.randomNumber = Math.random();
    next(response, true);
  }

};
```

**Comment by evantahler** [comment]
And middleware changes acordingly

**Comment by crrobinson14** [comment]
I'm confused - what is the goal of this change? Can you add some detail?

**Comment by evantahler** [comment]
One issue:

We should never try to update the state of the connection at the end of an action:  https://github.com/evantahler/actionhero/blob/master/initializers/actionProcessor.js#L81-L84
This can cause race conditions when reporting.  Rather, we should just pass the data to the callback.

In actions themselves, you shouldn't modify the connection (unless you are explicitly doing so, like with authentication).  Changing `connection.response` is really a lie here, as you are changing `actionProcessor.proxyConnect`.  The _originalConnection passthough to modify the connection itself is very misleading, as we are re-using the nouns.

**Comment by slattery** [comment]
I also need more info!    Are you unhappy with the vocab/terms or the functionality?    I thought _original's purpose was to help as we cascade over preProcessors, etc?

I have often found myself mining/comparing raw and _original with the higher level connection.   I agree it is hard to track persistent stuff, and the vocab can be slippery, so I somethings hang my own objs on connection.   IIRC autosession does this too.    For SCIENCE I plugged in passport.js and needed to access/pass req and res from raw and found that all made perfect sense, not that raw is under scrutiny...

I have thought it very clever to leave everything nuts-and-bolts in raw and _original.   Most useful is fingerprint for ex: it has been great tying in the first vanilla HTTP and XHR requests with WS messaging.

So I'm hungry for more discussion about this, to see how it could be made better in your opinion.

**Comment by evantahler** [comment]
I'll add some code soon in a PR we can talk about (talking in the abstract is hard).  Basically, more and more folks expect changes to the `connection` object to persist.  Middleware doing `connection.authorized = true; connection.userId = 123` is expected to work.  While the `_originalConnection` stuck was a hack to expose the underlying object, I do think we can do better ro reduce confusion for new folks. 

In @slattery's examples, you would still have access to `connection.rawConnection` and fingerprint would promote to `connection.fingerprint`.

The reason for _originalConnection was to pass a "snapshot" of the state of the params to each action, but if we split out the snapshot as a separate argument to the middleware and actions (see above psudeo code), there's no reason to make the snapshot.

**Comment by crrobinson14** [comment]
Oh, I see now what you mean. Yes, we're hacking around this ourselves. It's especially important for long-lived connections like WebSocket requests.

**Comment by evantahler** [comment]
Solved by https://github.com/evantahler/actionhero/pull/615
