### ISSUE TITLE
get redis size when starting

### ISSUE THREAD

**Issue by zitang** [evantahler/actionhero#563]
In initializer cache#start method , the size of redis keys will be counted and then be printed.
it's good to get cache size but the time complexity for this operation is O(N), it will block cache initializer if there are lots of keys, like 1m.

Hope to remove it or use a configurable parameter to disable it. Thanks.

http://redis.io/commands/KEYS

**Comment by evantahler** [comment]
The keys command (as you note) is certainly slow, and I agree that this is a silly thing to do at boot.  The method can remain of corse, but we shouldn't invoke it automatically.
  
Removed! 7ed35674e3c2916d95e9e56c9927ff5ed6926306
