### ISSUE TITLE
Socket already in use

### ISSUE THREAD

**Issue by MacTynow** [evantahler/actionhero#565]
Hi,

I am running actionhero behind an nginx and use unix socket files. However, when the actionhero process crashes, the socket file is not deleted (not surprising), but when forever brings it back up, it can't use the socket file again since it is 'already in use', and so my process keeps restarting in a loop.

This is similar to the issue those guys reported on puma (I know, it is not node.js) : https://github.com/puma/puma/issues/73

Am I doing something wrong, or is it a possible improvement? 

(I might take a look and do a pull request myself tomorrow, but I'm not such a node.js genius at all)

Thank you!

**Comment by evantahler** [comment]
What version of actionhero are you using?  We should already be accounting for this:

1) try 5 times to 'boot' the webserver and bind to the socket file https://github.com/evantahler/actionhero/blob/master/servers/web.js#L52-L66
2) If there is a failure, we then try to remove the file that's already there and try again https://github.com/evantahler/actionhero/blob/master/servers/web.js#L446-L456.

You may be having trouble if actionhero can't actually delete that socket file... perhaps the forever process is run by another user, sudo, etc.

**Comment by MacTynow** [comment]
Ho, right, we are using 8.0.1...

Sorry about that, thanks for the help.
