### ISSUE TITLE
Getting started feedback

### ISSUE THREAD

**Issue by ivancevich** [evantahler/actionhero#574]
Hello @evantahler and team. First I'd like to thank you for the awesome job you've done with Actionhero. It's being a great foundation to built on top of.
I'd like to give you some feedback on how I got started using the framework:

- Reading parameters values:
    It was difficult to me to know that I had to define the `inputs` property on an action, in order to be able to access a parameter I was expecting in a route `/users/:userId`. If I didn't add the `userId` into the `inputs` prop, I couldn't access `connection.params.userId`.

- Reponding with errors:
    It was hard to me to be able to respond with other status codes than `200`. I found the solution in a GitHub issue. It would be nice to have something like this: `connection.error(404, "User not found");`

- Routes grouping:
    As far as I know, routes are grouped by HTTP method. I think it would be nice to be able to have a `/routes` directory and define them into separates files, like this:
```
/routes
    users.js
    cars.js
    ...
```

That's all I have for now. Hope that helps to keep improving Actionhero.
I'm using it on a personal project I'm working on weekend, so hopefully I can contribute on the framework soon.
Cheers!

**Comment by S3bb1** [comment]
Hi @ivancevich 

1. question:
you can set the parameter 
```javascript
// disables the whitelisting of client params
disableParamScrubbing: false,
```
in config/api.js to disable the param validation on every route

2. question:
you can respond with different status codes if you set connection.rawConnection.responseHttpCode to return status codes like 404 or 204 ;-)

Greets ;-)

**Comment by ivancevich** [comment]
Hi @S3bb1 thanks for your quick reply.

I didn't know about the `disableParamScrubbing` property. It's nice to have that. The thing is, if I would like validation to be optional, say I want to be able to read the `connection.params.userId` parameter no matter if there is validation or not.

For the 2nd answer, I already knew that. All what I'm saying is quite hard to find that, and not very handy. It'd better to have something like: `connection.error(404, "User not found");`

What do you think?

**Comment by S3bb1** [comment]
If you want the validation to be optional for a special parameter you can adjust the array in https://github.com/evantahler/actionhero/blob/master/initializers/params.js#L8 there are special paramters stored which arent checked.

hmm another method is to set connection.error to a string ... then it will be send as HTTP StatusCode 400 look here -> https://github.com/evantahler/actionhero/blob/master/servers/web.js#L240 .. maybe this comes near to your request ?

**Comment by ivancevich** [comment]
Ok, I'll look into that. Thanks @S3bb1 !!

**Comment by evantahler** [comment]
Looks like @S3bb1 took care of this! 
Closing.
