### ISSUE TITLE
websocket wrong params order.

### ISSUE THREAD

**Issue by rootStar-lock** [evantahler/actionhero#575]
It seems [websocket server][1] does not keep params in right order. In our case "room" and "message" params messed up. Why does it iterate message as array and not dictionary?

   [1]: https://github.com/evantahler/actionhero/blob/master/servers/websocket.js#L230

**Comment by evantahler** [comment]
Can you provide an example of what you are seeing?  "words" is for the chat system, params is for actions.

**Comment by rootStar-lock** [comment]
We use https://github.com/seegno/primus-objc and can't ordering params that sends to websocketserver
In data log we see 2015-02-03 19:23:27.917 Primus-ios-test[12032:3805114] Sent outgoing::data: {"message":"test","event":"say","room":"defaultRoom"}

In this case handleData recieve {"message":"test","event":"say","room":"defaultRoom"}, after that AH remove "event" key and store data object into array "words" like ['test', 'defaultRoom']. In verbs [processing][1] AH make mistake and try to send message='defaultRoom' to room='test'.   

   [1]: https://github.com/evantahler/actionhero/blob/master/initializers/connections.js#L256

**Comment by rootStar-lock** [comment]
Debug level output:
2015-02-04 13:08:19 - debug: [server: websocket] verb verb=say, to=192.168.10.17, params=["test","defaultRoom"]

**Comment by cfr** [comment]
Hey Evan, I'm mobile developer working with @rootStar-lock. Do you need additional client-side info to clarify this issue?

**Comment by evantahler** [comment]
ahh! It looks like this is actually the problem here: https://github.com/evantahler/actionhero/blob/master/servers/websocket.js#L230

The good news is since `say` is the only "verb" that relies on message order, it should be easy to fix.  I'll take a look in a few days.

**Comment by evantahler** [comment]
This will be solved here https://github.com/evantahler/actionhero/pull/577/files

**Comment by evantahler** [comment]
This will be solved here https://github.com/evantahler/actionhero/pull/577
