### ISSUE TITLE
 'content-type' field is undefined when use XDomainRequest

### ISSUE THREAD

**Issue by enginespot** [evantahler/actionhero#579]
for IE 8 9 10 ,  for a CROS post request ,  we can only use  XDomainRequest

but when use it , the request header 'content-type' will be undefined and also we can not use middleware fix it .

**Comment by enginespot** [comment]
'''
var HeaderFix;
HeaderFix = (function() {
  function HeaderFix(api) {
    var EmptyFunc, orignalEvent;
    this.api = api;
    EmptyFunc = function(connection, actionTemplate, next) {
      next(connection, true);
    };
    api.actions.addPreProcessor(EmptyFunc);
    orignalEvent = api.servers.servers.web._events['connection'];
    api.servers.servers.web._events['connection'] = function(connection) {
      if (connection.rawConnection.req.headers["content-type"] === void 0) {
        connection.rawConnection.req.headers["content-type"] = "application/x-www-form-urlencoded";
      }
      orignalEvent(connection);
    };
  }
  return HeaderFix;
})();


exports.headerFix = function(api, next) {
  api.headerFix = new HeaderFix(api);
  next();
};
'''
currently we add the above code fix the bug , hope that in future we can find a good solution.

Thanks.

**Comment by evantahler** [comment]
The problem is probably here (https://github.com/evantahler/actionhero/blob/master/servers/web.js#L363) with the form parser.  Does this only happen with POST/PUT requests?  I assume GET is OK?  

Send in a pull request! (It will be important that you also provide a test that demonstrates this.  I imagine crafting a relevant test will actually be harder than the solution)

**Comment by enginespot** [comment]
yes , it is the problem , since that there is no content-type header when use xdomainrequest

currently our team add a fix by the way

if (connection.rawConnection.req.headers["content-type"] === void 0) {
        connection.rawConnection.req.headers["content-type"] = "application/x-www-form-urlencoded";
}

**Comment by evantahler** [comment]
Sure, please send a Pull request!   You can probably add that code around here https://github.com/evantahler/actionhero/blob/master/servers/web.js#L199

I'm unable to test this, so I'm relying on you.

**Comment by enginespot** [comment]
I read the web.js ,and maybe I find a better solution ,
add process request event to server , then for clientside , we can custom it , if you think so , I will try to pull a request .
```
var http = require('http');
      server.server = http.createServer(function(req, res){
        server.emit('preProcessRequest', res);
        handleRequest(req, res);
        server.emit('postProcessRequest', res);
      });
```

**Comment by evantahler** [comment]
I'm not sure what you are showing us here.  Why are you making a new HTTP server?

**Comment by enginespot** [comment]
it is not create new HTTP server , it is exist in web.js file
https://github.com/evantahler/actionhero/blob/master/servers/web.js#L41

what I do is only add 

server.emit('preProcessRequest', res);
server.emit('postProcessRequest', res);

then maybe actionhero can public handleRequest to user

**Comment by evantahler** [comment]
I'm having trouble understanding why you want extra emitters. The web
server should also be hard to access out of scope.  I thought you just
wanted an extra "if" to handle missing headers?

Please send a pull request so we can see what you have in mind!  I'm
locking this issue, and we can continue discussing code.  It will be much
clearer that way.

On Friday, February 13, 2015, Edwin Liu <notifications@github.com> wrote:

> it is not create new HTTP server , it is exist in web.js file
> https://github.com/evantahler/actionhero/blob/master/servers/web.js#L41
>
> what I do is only add
>
> server.emit('preProcessRequest', res);
> server.emit('postProcessRequest', res);
>
> then maybe actionhero can public handleRequest to user
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evantahler/actionhero/issues/579#issuecomment-74228496>
> .
>


-- 
Let's blame the phone for the typos...
