### ISSUE TITLE
Got wrong initializer name if the full path includes '.' before file name

### ISSUE THREAD

**Issue by jacobbubu** [evantahler/actionhero#585]
For example, if the initializer in a folder that has the full path includes '.'
`/Users/xxx/y.z/node_modules/actionhero/initializers/actionProcessor.js`

The line https://github.com/evantahler/actionhero/blob/master/actionhero.js#L96 will extract out the initializer name as  `/Users/xxx/y`.

**Comment by S3bb1** [comment]
Hi,

this was already fixed few days ago with pull request https://github.com/evantahler/actionhero/pull/581

**Comment by evantahler** [comment]
Thanks folks!
