### ISSUE TITLE
About 'remotePort is required to create a new connection object' error

### ISSUE THREAD

**Issue by Frankzhaopku** [evantahler/actionhero#589]
Hello, I'm a fresh node.js developer from China using actionhero as our App API server's main framework. I occasionally got this error which makes the server exit, the trace stack is:

```
/home/zhaoshengyu/Sagittarius/node_modules/actionhero/initializers/connections.js:109
      if(data[req] === null || data[req] === undefined){ throw new Error(req +
                                                               ^
Error: remotePort is required to create a new connection object
    at /home/zhaoshengyu/Sagittarius/node_modules/actionhero/initializers/connections.js:109:64
    at Array.forEach (native)
    at api.connection.setup (/home/zhaoshengyu/Sagittarius/node_modules/actionhero/initializers/connections.js:108:57)
    at new api.connection (/home/zhaoshengyu/Sagittarius/node_modules/actionhero/initializers/connections.js:84:10)
    at api.genericServer.buildConnection (/home/zhaoshengyu/Sagittarius/node_modules/actionhero/initializers/genericServer.js:54:22)
    at handleConnection (/home/zhaoshengyu/Sagittarius/node_modules/actionhero/servers/socket.js:196:12)
    at Server.<anonymous> (/home/zhaoshengyu/Sagittarius/node_modules/actionhero/servers/socket.js:43:9)
    at Server.emit (events.js:95:17)
    at TCP.onconnection (net.js:1191:8)
```

But actually in my server, I set TCP socket disenbled and only use websocket as my protocol, what would be the problem?

PS. I got two more questions here. 1. How to enable both HTTP protocol and an upper one at same time, like websocket or socket.io. 2. Can I config my own server with socket.io as transfer protocol? What should I do? Thanks.

**Comment by evantahler** [comment]
How are you making connections?  Are you using the built in servers?  What OS, node version, and actionhero version are you using?

You can enable multiple servers simply with the [config files](https://github.com/evantahler/actionhero/blob/master/config/servers/web.js#L5) (`enabled = true`) that are generated along with a new project.  Actionhero comes with a web (http/s), websocket (primus), and tcp server.    Yes, the websocket server requires the web server. 

You can [choose the underlying websocket](https://github.com/primus/primus#supported-real-time-frameworks) transport you want with primus (like engine.io).

**Comment by evantahler** [comment]
Closing due to lack of communication

**Comment by Frankzhaopku** [comment]
Sorry for not replay in time and happy Chinese New Year. We use Java-websocket as our Android connection tool. The OS is CentOS 6.6 with actionhero 9.4.1 and node v0.10.33. The error still happens today. PS. when I use test environment, the error happens, but the error never shows under production environment.

**Comment by evantahler** [comment]
If you are only seeing the error in `test`, I'll bet that the java websocket is doing some strange things.  Can you confirm that browers-based ws is OK?  Also, please try out actionhero 10.x.  We've made a number of fixes since then.

**Comment by Frankzhaopku** [comment]
OK, thanks. We don't have a browser client but we have some debug tools using websocket-js and they work well. I will upgrade soon and thank you again.
