### ISSUE TITLE
RESTful responses

### ISSUE THREAD

**Issue by DoctorDimon** [evantahler/actionhero#591]
Hello!

Can you tell me, how can I send corrent HTTP code with response from an action. For example, if I request "create" action, I want to repond with 201 Created HTTP Code and response body.

Thanks!

**Comment by S3bb1** [comment]
Hi,

you can respond with different status codes if you set 
```javascript
connection.rawConnection.responseHttpCode
```
to return status codes like 404 or 204 ;-)

Greets ;-)

**Comment by DoctorDimon** [comment]
Tnx! )
