### ISSUE TITLE
Detect HTTP request type?

### ISSUE THREAD

**Issue by DoctorDimon** [evantahler/actionhero#592]
Hello again.

Im creating a RESTfull API, and i didn't find a solution how detect HTTP request type (GET, POST, PUT, DELETE).

Also I want to ask you, what is the better solution for this case. So I have one action name, "/api/action_name", and I need different behavior of this action depend on HTTP request type. Should I do such routing in action file or maybe in routing?

**Comment by S3bb1** [comment]
HI,

if i see it right in the https://github.com/evantahler/actionhero/blob/master/servers/web.js#L210 you see the method in connection.rawConnection.method.

But anyway i would prefer define the specific actions in the routes.js.

**Comment by DoctorDimon** [comment]
Tnx, now I know where I can get it.

But how can I define specific actions in router base on request method?

**Comment by S3bb1** [comment]
Hi,

this is commented out in the https://github.com/evantahler/actionhero/blob/master/config/routes.js

there you can see the specific arrays for GET, POST, PUT,... Methods.

**Comment by DoctorDimon** [comment]
This is what im looking for!

Cool! Thanks!

**Comment by evantahler** [comment]
Thanks @S3bb1!
