### ISSUE TITLE
File Watchers Broken

### ISSUE THREAD

**Issue by genexp** [evantahler/actionhero#603]
Hey Team - This recent change:
  https://github.com/evantahler/actionhero/blame/master/initializers/configLoader.js#L22

broke the custom file watchers:
  http://www.actionherojs.com/docs/core/development-mode.html#watching-custom-files

With the following error:

    Cannot find module 'lib/validators.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
    at /Users/brian/code/app/actionhero-service/node_modules/actionhero/initializers/configLoader.js:22:44
    at process._tickDomainCallback (node.js:381:11)

**Comment by evantahler** [comment]
I'm unable to reproduce this.  Can you share some more code/your file hierarchy?

I did find a bug where some custom initializers weren't getting watched (if they didn't have a init method).  Fixed here https://github.com/evantahler/actionhero/commit/b8c503c517f03d53b69c90d095d929cbddaf0ea3

I also added some path normalization to the watch method... which might have been your issue?

**Comment by genexp** [comment]
Hey Evan - Absolutely!  I created an initializer to watch my lib folder.  Here's what I have:

````
var glob = require("glob")
var _    = require("lodash")
module.exports = {
  initialize: function(api, next){
    glob("lib/*.js", {}, function (err, files) {
      _.each(files, function(file){
        console.log(file);
        api.watchFileAndAct(file, function(){
          api.log('rebooting due to config change: ' + file, 'info');
          api.commands.restart.call(api._self);
        });
      });

    next();
    });
  }
};
````

**Comment by evantahler** [comment]
Oh, that's just something wacky with the way that `glob` is dealing with the files.  It's hard to say what they are relative to, so absolute paths are always best:

```js
var glob = require("glob");
var _    = require("lodash");

module.exports = {
  initialize: function(api, next){
    glob("lib/*.js", {}, function (err, files) {
      _.each(files, function(file){
        api.watchFileAndAct(__dirname + '/../' + file, function(){
          api.log('rebooting due to config change: ' + file, 'info');
          api.commands.restart.call(api._self);
        });
      });

    next();
    });
  }
};
```

**Comment by genexp** [comment]
Ahhh. I should have noticed that.  Thanks dude!
