### ISSUE TITLE
<action>.inputs copied to all actions

### ISSUE THREAD

**Issue by justingosan** [evantahler/actionhero#605]
Hi! 

It's pretty straightforward:

I have 'actionHistory' parameter defined only for POST /history route.
![](https://lh6.googleusercontent.com/-XSG3aN3eFKw/VO9CZEru5qI/AAAAAAAAFX0/yj22nnmBB_Y/s0/2015-02-26_23-57-21.png)

When I query PUT /location (a different action in a different file in a different route) with the actionHistory parameter it fills in.
![](https://lh3.googleusercontent.com/-8GCcEvjiYh4/VO9DkKcnMSI/AAAAAAAAFYA/lo3JdaiUsJ8/s0/2015-02-27_00-02-24.png)

Are defined inputs for ONE action really defined for ALL actions? If this this the case, wouldn't it make much more sense to declare the inputs variable globally rather than inside individual actions? Let me know your thoughts. :)
Using "actionhero": "10.0.4"

Thanks!

**Comment by justingosan** [comment]
My bad. I totally missed this in the docs:
`actions.inputs are used for both documentation and for building the whitelist of allowed parameters the API will accept. Client params not included in these whitelists will be ignored for security. If you wish to disable the whitelisting you can use the flag at api.config.general.disableParamScrubbing. Note that Middleware preProcessors will always have access to all params pre-scrubbing.`

Sorry! Will close this now.

**Comment by evantahler** [comment]
Your original thought was correct. That was a bug that was fixed in the latest release. https://github.com/evantahler/actionhero/issues/582
