### ISSUE TITLE
custom action input validators suddenly do not work

### ISSUE THREAD

**Issue by justingosan** [evantahler/actionhero#606]
Hi!

Not totally sure what happened but I did a quick update earlier and now even the validators from the tutorial (http://www.actionherojs.com/docs/core/actions.html) do not work. 

I don't have much time right now to investigate so here's a quick screeny

![](https://lh5.googleusercontent.com/-dWjBx59Xh_Y/VPR6lFmkkcI/AAAAAAAAFZQ/IuHtwp03hP8/s0/2015-03-02_22-58-25.png)

The validator for actionHistory is simply
```
validator: function(param) {
                  if(param.length < 4){
                    return new Error('password should be at least 3 letters long');
                  }else{
                    return true;
                  }
                }
```

I'll investigate and provide more info a bit more later when I have more time.
Using ├─┬ actionhero@10.1.0

**Comment by evantahler** [comment]
That line indicates you are missing a config from `config/errors.js`, specifically this: https://github.com/evantahler/actionhero/blob/master/config/errors.js#L22-L24

**Comment by justingosan** [comment]
thanks! weird though, I never edited that particular file and it seemed to
work perfectly before.

Justin Sanciangco
Web Developer - @justingosan <http://blog.jz10.info>
