### ISSUE TITLE
Set a custom cookie

### ISSUE THREAD

**Issue by DoctorDimon** [evantahler/actionhero#611]
Hello!

I can't figure it out, how to set a custom cookie with ActionHero? Can you please explain me that?

**Comment by evantahler** [comment]
these types of questions are best to ask on the mailing list/gitter.

you can mess with `connection.rawConnection.responseHeaders`, and from there declare a set-cookie header

**Comment by DoctorDimon** [comment]
I had found that, BUT in your documentation i found this - 

connection.rawConnection.responseHeaders: array of headers which can be built up in the action. Headers will be made unique, and latest header will be used (**except setting cookies**)

**Comment by evantahler** [comment]
that means you can set multiple cookies at once!  If you do multiple set-headers for other things (like changing a mime-type) only the most recent one will be used.

**Comment by DoctorDimon** [comment]
Oh, now I've understood. Tnx!
