### ISSUE TITLE
FlatFile cache should specify public

### ISSUE THREAD

**Issue by genexp** [evantahler/actionhero#613]
Hey Y'all - 

I think we need to add "public" here.  Upstream clients don't cache unless it's explicit (at least, Chrome doesn't seem to be).

 https://github.com/evantahler/actionhero/blob/8c886db63322d614978eaf85c4989be43fc7b8b3/servers/web.js#L103

**Comment by evantahler** [comment]
You got it! 
https://github.com/evantahler/actionhero/commit/33225a6b35effd3da7c2e06a51596e15d57b86ed
