### ISSUE TITLE
queued tasks don't run  

### ISSUE THREAD

**Issue by levansuper** [evantahler/actionhero#614]
I have a problem when the tasks don't run.

```
task:
var task = {
    name: "sendWelcomeEmail1",
    description: "I will send a new user a welcome email",
    queue: "default",
    plugins: [],
    pluginOptions: [],
    frequency: 111,
    run: function(api, params, next) {
        console.log(55555);
        next();

    }
};

exports.task = task;
```

```
task config:
exports.default = { 
  tasks: function(api){
    return {
      scheduler: true,      
      queues: ['*'],
      timeout: 1000,
      redis: api.config.redis
    };
  }
};
```

it logs this: 
2015-03-16 17:39:13 - info: enqueuing periodic task: sendWelcomeEmail1
but the task doesn't run (doesnt log ("55555"))

P.S. i'm using 10.1.0 version of actionhero.

**Comment by evantahler** [comment]
Looks like you don't have any workers.  Check for a config option like this: https://github.com/evantahler/actionhero/blob/master/config/tasks.js#L12-L14

**Comment by levansuper** [comment]
that was the case. I set maxTaskProcessors: 1 and it works now.
 thank you!
