### ISSUE TITLE
Automatically re-enqueue failed tasks, perhaps based on configuration?

### ISSUE THREAD

**Issue by awinder** [evantahler/actionhero#617]
I'm noticing (though I've only been playing around with this for a short time, so apologies if this is my error!) that tasks which fail with errors don't seem to be re-enqueued.  I checked out the docs and didnt really notice too much around this feature, so I'm wondering about integrating something like that?

I'm sure I can just implement this using the node-resque hook points, but it seems like a pretty common use-case.

**Comment by evantahler** [comment]
There isn't any automatic re-enquing of failed jobs by default (jobs could be expensive, time-dependant, etc).  Ruby's resque is the same way, and they have a mature collection of retry backends (exponential backup, retry-with-lock, etc).   I don't think I've seen any like that with node-resque yet sadly. 

It looks like you are about to publish a node-resque plugin!

**Comment by evantahler** [comment]
Open an issue in node-resque if you need any help

https://github.com/taskrabbit/node-resque

**Comment by awinder** [comment]
Thanks much!
