### ISSUE TITLE
action/generateAction questions

### ISSUE THREAD

**Issue by hippich** [evantahler/actionhero#618]
I noticed that manual shows example of action looking like this (http://www.actionherojs.com/docs/core/actions.html) :
```javascript
exports.randomNumber = {
  name: "randomNumber",
  [...]
};
```

Where generated action via `actionhero generateAction --name=randomNumber` produces following output:

```javascript
exports.action = {
  name:                   'randomNumber',
  [...]
};
```

Notice `randomNumber` vs. `action` different after `exports.`.

Question - which one is correct? And if both are correct - what difference between these two?

**Comment by evantahler** [comment]
Either will work!  We use the `name` attribute to truly determine the name of the action.   

If you have more than one action per file, you'll need to come up with more than one exports name :D

**Comment by evantahler** [comment]
I'll update the docs to just say `action` to be consistent

**Comment by hippich** [comment]
Got it! Thanks!
