### ISSUE TITLE
Custom JSON formatting for errors

### ISSUE THREAD

**Issue by awinder** [evantahler/actionhero#620]
I'd love to utilize the input validation inside of actions, but I'm having trouble finding info on how I could customize the error responses that my API will then send back.  I see where I can manipulate some of the messages, but what I'd really need is the ability to manage the entire json response format.  This is particularly important for those of us working with hypermedia formats to be able to implement error / exception responses that are valid for the format

**Comment by evantahler** [comment]
In the [v11 version of actionhero](https://github.com/evantahler/actionhero/milestones/v11.0.0) (which is coming out in the next month or so) you can create JSON object error responses, IE:

```javascript
exports.action = {
  name:                   'complexError',
  description:            'complexError',
  blockedConnectionTypes: [],
  outputExample:          {},
  matchExtensionMimeType: false,
  version:                1.0,
  toDocument:             true,

  inputs: {},

  run: function(api, data, next){    
    var error = {
      a: 'b',
      thing: { stuff: 'The Error' }
    };

    next(error);
  }
};
```

**Comment by evantahler** [comment]
I've codified this with some new tests here https://github.com/evantahler/actionhero/pull/624

**Comment by kytwb** [comment]
Doesn't seem to work with instances of `Error`, just return a string. Maybe because some properties are not enumerable on `Error`?

**Comment by kytwb** [comment]
@evantahler I think this is due to `servers/web.js:262`:
```
if(data.response.error && util.isError(data.response.error)){
  data.response.error = String( data.response.error.message );
}
```

**Comment by evantahler** [comment]
@kytwb I think this behavior is correct.  When returning a response via JSON (which the web server does), we need to 'stringify' everything, thus flattening all objects.  The error is returned from the action (or middleware) in its native type (`new Error()`), and the server then modifies the response payload to be appropriate for the transport. 

How would you want errors returned via JSON/HTTP?

**Comment by lorenzofox3** [comment]
@evantahler The problem is that you might want to extend the Error prototype to benefits from the stack trace etc but add some capabilities. A popular library is for example https://www.npmjs.com/package/http-errors 
but the custom properties you may define won't be in the payload, only the message

**Comment by evantahler** [comment]
Hmn... does that mean we need a custom serialization function (which defaults to `String()`)?.  Send in a pull request!

**Comment by kytwb** [comment]
Why not just removing [this part](https://github.com/evantahler/actionhero/blob/master/servers/web.js#L261-L263) of the web server?

**Comment by evantahler** [comment]
I want to keep some sort of default serialization ability for errors... but what about this?  we can move error object serialization to the config file, this way you can change it to be whatever you want!

https://github.com/evantahler/actionhero/pull/670

**Comment by evantahler** [comment]
Actually, lets keep this issue closed... move all commenting to #670!
