### ISSUE TITLE
actions/connection

### ISSUE THREAD

**Issue by hippich** [evantahler/actionhero#627]
playing a bit with servers i stumbled upon, what seems like, design issue/feature. I am using custom Server to define connection with RabbitMQ, but I create connection only once, and call server.processAction() everytime message from RMQ arrive. Which quickly proved to be not quite right approach, since data passed using `connection` object and it is quite possible new message arrive before previous message get processed. So race conditions quite can happen.

So it looks like I have to create `connection` object for each new message arrived and treat each message as a separate connection. Is this is correct assumption? Any other ideas on how to implement long-lived connections?

I am looking at Socket server, and it looks like it potentially can experience same issue I am dealing with right now, since same `connection` being recycled every time .processAction() is called, and if action happen to be async and have a large delay it is quite possible it will be finished and changes, lets say, `.error` before second .processAction() get processed.

**Comment by evantahler** [comment]
You have the right idea!   [Here's an example that connects to twitter](https://github.com/evantahler/actionhero-tutorial) and just like you are doing with RabbitMQ, handles each message.  

You should create a new connection per message, like we are doing here: https://github.com/evantahler/actionhero-tutorial/blob/master/servers/twitter.js#L51-L69.  If you don't want to create a new connection per each message, you can just call any function you like... perhaps an aciton doesn't need to be called?

**Comment by hippich** [comment]
I still want this action to be callable from web/socket/websocket, so action must be used (unless there is other way?)

I guess "connection" was confusing to me, this is really more like a "request"-type of thing in its own nature.

Thank you for confirming it. I will try using connection-per-message to see how it goes.
