### ISSUE TITLE
Different task frequency for test

### ISSUE THREAD

**Issue by mstdokumaci** [evantahler/actionhero#634]
Is there a way of chaning task frequency for periodic tasks, depending on environment? Sometimes developer may need different frequency for testing.

**Comment by evantahler** [comment]
Sure...

```javascript
var frequency = 1000;
if(process.env.NODE_ENV === 'production'){
  frequency = 5000;
}

var task = {
  name:          'doStuff',
  description:   'I will do some stuff',
  queue:         'default',
  plugins:       [],
  pluginOptions: [],
  frequency:     frequency,
  run: function(api, params, next){
    // stuff
    next();
  }
};

exports.task = task;

```

**Comment by evantahler** [comment]
You can also require a 'development_settings' file if it exists or similar.

**Comment by mstdokumaci** [comment]
I was mistaken by thinking that process.env.NODE_ENV was not set yet while loading tasks. Thanks for the answer.
