### ISSUE TITLE
connection.id as a session id?

### ISSUE THREAD

**Issue by hippich** [evantahler/actionhero#636]
I found this gist - https://gist.github.com/evantahler/4326070

It uses connection.id as a cache key, which doesn't work currently, since each request connection.id is being changed a bit. But I noticed I can use first part of connection.id so far. Is this is correct assumption, or I can not rely on this and there is some kind of separate session id available?

**Comment by evantahler** [comment]
Yeah, that's an old gist :D

The first part of `connection.id` is the same as `connection.fingerprint` which, for HTTP connections, comes from the session cookie.  So yes, that is a save cache key.

**Comment by hippich** [comment]
Thanks!
