### ISSUE TITLE
--node options with --daemon key

### ISSUE THREAD

**Issue by rootStar-lock** [evantahler/actionhero#644]
Is there any any cli options to send params like: --expose-gc, --nouse-idle-notification, to node when i'm start with --daemon key?

**Comment by evantahler** [comment]
no, you would need to send these manually:  `node --expose-gc --nouse-idle-notification ./node_modules/.bin/actionHero start --daemon `

**Comment by rootStar-lock** [comment]
Sorry but this don't work for me.
In fork I just add ```data.response.gc_exposed = global.gc ? true : false;``` to __actions/status.js__ 
and run `$ node --expose-gc --nouse-idle-notification bin/actionhero start --daemon` gc_exposed was __false__ all the time.
iojs v1.8.1
