### ISSUE TITLE
complex input in actions

### ISSUE THREAD

**Issue by levansuper** [evantahler/actionhero#649]
Since I'm using Mongodb i wanted to have ability to have ability to have some complex parameters in actions like: 

```
inputs : {
    a : {
        b: { 
            c : { required : false},
            d : [{required : true}]
        }
   }
} 
```

in this case a.b.d is an array and will always be required and a.b.c is optional
the syntax may be different but that's what i need and would like to implement.

**Comment by evantahler** [comment]
Sorry, this is not something actionhero will support.  A POST (or GET, or PUT, etc) in your example would only have one param, `a={"b":{'c":"thing","d":"other_thing"}}`.   Your request presumes that prams are 1) JSON and 2) parseable.  What about XML payloads?  What about Files?  

I would suggest that you create a small middleware to pre-process `params` against `action.nestedParamRequirements` which you can append to your action definitions.

**Comment by levansuper** [comment]
in my example a is one of fields that can be added.

like: 

a : {
        b: { 
            c : { required : false},
            d : [{required : true}]
        }
   },
e : {

}

One more question related to that.
are you going to support types in the input fields or this will remain the job of the validator function?

**Comment by evantahler** [comment]
Yeah, type checking/conversion will always be left up to the implementer.  Because we aren't coupled to any specific front-end, we can't ask for input valuation before hand, nor can we make assumptions based on the string content (all params always come in as strings).

**Comment by evantahler** [comment]
will be solved via https://github.com/evantahler/actionhero/pull/711
