### ISSUE TITLE
How to implement client chat example with FayeCpp?

### ISSUE THREAD

**Issue by katopz** [evantahler/actionhero#656]
Far as I know There is no actionheroClient.js in cpp,
The closet one I get is [FayeCPP](https://github.com/OlehKulykov/FayeCpp) so I'm gonna start my journey with this.

I'm now able to get client state at ```onFayeTransportConnected``` and in my terminal said
```
2015-05-14 13:09:23 - info: [server: websocket] new connection to=127.0.0.1
```
Which should mean transporter and connection is ready.

But when it try to [handshake](https://github.com/OlehKulykov/FayeCpp/blob/master/src/FCClient.cpp#L587), nothing getting back...
FYI : refer to https://github.com/OlehKulykov/FayeCpp/blob/master/src%2FFCClient.cpp#L88
```objc
	static const char * const _bayeuxHandshakeChannel = "/meta/handshake";
	static const char * const _bayeuxConnectChannel = "/meta/connect";
	static const char * const _bayeuxDisconnectChannel = "/meta/disconnect";
	static const char * const _bayeuxSubscribeChannel = "/meta/subscribe";
	static const char * const _bayeuxUnsubscribeChannel = "/meta/unsubscribe";
```
Not sure is this need to change? or maybe some where else? (Yes, I'm kinda lost)

- - -
So the question is
* How to do proper handshake via Faye? (request is send but get nothing back)

Thanks

**Comment by evantahler** [comment]
Nice! I love seeing folks use actionhero to talk to other apps/languages.  

The first (and obvious thing) is to make sure that you are telling actionhero's websocket server (via Primus) to actually use faye.  By default we use a raw websocket connection.  You'll need to change the config https://github.com/evantahler/actionhero/blob/master/config/servers/websocket.js#L25 and be sure to `npm install faye`.  More details on swapping the underlying transports for primus can be found in the [primus readme](https://github.com/primus/primus#faye)

Ok, so once you can connect, the next thing to do is actually preform the actionhero handshake (which happens after the faye/WS protocol handshake).  You can see what happens in the client-side JS: https://github.com/evantahler/actionhero/blob/master/client/actionheroClient.js#L37-L58.  There isn't much, we just call the `detailsView` verb to load in our own `clientId` and check any rooms we might be connected to.  

What's important on the server side: https://github.com/evantahler/actionhero/blob/master/servers/websocket.js#L198-L205.  When primus, via faye in your case, says we have a new connection, we build up the actionhero `connection` object.  There are a lot of assumptions here about this being a websocket (we even try to parse headers if they exist).  If you see anything failing here, let me know in a new issue, and we can make this more generic for non-browser webcosket implementations. 

---

As a note, I know some folks have used actionhero (via faye) to talk to IOS apps, so https://github.com/pcrawfor/FayeObjC might be useful to check out as well.

**Comment by katopz** [comment]
Cool! Thanks for more detail. For now, I think I need more experience with Primus and Faye.
So I decide to have fun with Primus ObjC first and I will get back to this again when I know what I"m doing.

Here's what I got today (prove of concept) : https://github.com/katopz/primus-objc-helloworld
and my next step is try to port some function from actionheroClient.js -> swift/objc
I know! it's sound bummer but It's my bad habit to learning from working code.

You can close this issue for now. :D

Cheers!

**Comment by evantahler** [comment]
Awesome start!  Post this on the mailing list!

I'm no objC exert, but you *may* have some problems with the closures introduced on data (if you deallocate the primus connection, I don't think those closures will be garbage collected, as you keep making new ones each callback).  Also, the Primus library seems a little strange requiring "string" events, but if it works, it works!
