### ISSUE TITLE
Testing passport.js middleware: data.connection.rawConnection.req is undefined inside a testServer instance

### ISSUE THREAD

**Issue by justingosan** [evantahler/actionhero#659]
Hi!

So I've implemented a passport.js middleware based on the one posted on actionherojs.com https://gist.github.com/juancgarcia/e4caf5dc7474769f5137 (adapted to recent middleware syntax changes).

My problem comes about when running **mocha tests**. By design, passport.js is supposed to add in a few methods to the http request object (e.g req.isAuthenticated: https://github.com/jaredhanson/passport/blob/a892b9dc54dce34b7170ad5d73d8ccfba87f4fcf/lib/passport/http/request.js#L74). It fails when I try to access it because **data.connection.rawConnection.req** comes out as **undefined** in the testServer instance. Contrary to this, when running production, **data.connection.rawConnection.req** is an instance of the **IncomingMessage** object and contains the added passport.js methods. As such everything works as expected when running the production server. 

Here's a snippet from my middleware based on the provided gist:
```
var doPassportAuthenticateMiddleware = {
            name: 'doPassportAuthenticate',
            global: true,
            priority: 1002,
            preProcessor: function(data, next) {
                    api.log('initialize passportAuthenticate');
                    // Do not try to authenticate if already logged in



                    // data.connection.rawConnection.req  == undefined
                    // when inside mocha tests
                    if (data.connection.rawConnection.req.isAuthenticated()) {
                        api.log('already authenticated, nothing for passport to do');
                        return next();
                    }



                    // Requires login
                    if (!!data.actionTemplate.authenticated) {
                        api.log('not yet authenticated, authorization required');
                        // passport expects the credentials in a 'body' key inside of
                        // the request object, we're fudging them in here
                        return doBasicAuth(util._extend({
                            body: data.params
                        }, data.connection.rawConnection.req), data.connection.rawConnection.res, data.connection, next);
                    }
                    api.log('authentication not necessary');
                    next();
            ....
```

My test code is pretty straightforward:
```
  describe('Action: User', function() {
    this.timeout(20000);
    before(function(done) {
        actionhero.start(function(err, a) {
            api = a;
            done();
        })
    });

    after(function(done) {
        api.mongoose.clearDB(function() {
            actionhero.stop(function(err) {
                done();
            });
        });
    });

    it('should create a user', function(done) {
        api.specHelper.runAction('postUserSignup', {
            username: 'username',
            password: 'password',
            email: 'email@email.com',
            organization: 'organization'
        }, function(response) {
            console.log(response);
            done();
        });
    });
```

I'll continue debugging the issue but any input would be greatly appreciated!
Thanks!
Justin

**Comment by justingosan** [comment]
Tried to model my tests after this https://github.com/evantahler/actionhero/blob/master/test/servers/web.js

Turns out the problem exists when using specHelper. Works fine when manually using **request** to do the http call.

**Comment by evantahler** [comment]
Yep! The specHelper just mocks requests (transport agnostic). If you want to test HTTP, you need to actually make HTTP requests :)

-
 Evan Tahler | evantahler@gmail.com | +1 (415) 413-8268
 evantahler.com | actionherojs.com

**Comment by justingosan** [comment]
Makes sense! Thanks!
