### ISSUE TITLE
Tasks get locked up and stop working after a few server restarts

### ISSUE THREAD

**Issue by Roam-Cooper** [evantahler/actionhero#663]
Our tasks have been getting locked up after server restarts and so I've been trying to go through the flow that they take and found that in the AH's task initialiser, enqueueAllRecurrentJobs calls function self.enqueue with parameters taskName and a lambda function (as callback) whereas the enqueue function seems to expect parameters taskName, params, queue, callback instead.

Our active version of AH is old (mid 2014~) but I thought I'd check in the newest version and it is the same.

Am I just seeing things? (Just trying to resolve why our tasks are locking up.)

---
I changed enqueueAllRecurrentJobs to call self.enqueue with the correct parameters and it seems as if it should should be this way.

It does not completely resolve our locked task problems, which seem to be related to workers taking out locks on tasks and not releasing them for some reason (perhaps because the worker might have a different name after a server reboot?) Suspect keys in redis seem to be 'lock' and 'workerlock', upon deletion of these keys the locked up tasks run once again. Was this resolved in a newer version of actionhero? If so, then I will find the fix and patch our version as we are not ready to upgrade yet.

**Comment by evantahler** [comment]
Recurrent jobs absolutely take out resque locks, and actionhero will not re-enqueue jobs that are locked (or that resque thinks are already running).  There's been a lot of talk about this in other threads [[ https://github.com/evantahler/actionhero/issues/654 ]], but here's a summary:

- You need to be sure you "gracefully" shut down your servers/workers (give them time to complete whatever they are working on).  If you don't the job gets "stuck" (locked).
- You can recover failed jobs and retry them if you choose
- You can recover stuck jobs and retry them if you choose
- You can remove stuck workers if you choose (which take any stuck jobs with them).  However, this is dangerous and the implementation of this changes based on the topology of your infrastructure.   The commands exist [[ http://www.actionherojs.com/docs/core/tasks.html#failed-job-management ]] for you to make your own initializer or gunt task to help here.

**Comment by evantahler** [comment]
If there's more info you need, or this doesn't help, please open a new issue

**Comment by Roam-Cooper** [comment]
Okay, since we're on the old version, I'll write the code required to fix the lock up if the server is not restarted gracefully (which happens sometimes, it's nice to have tasks still run after this event).

But is 'enqueueAllRecurrentJobs' in Actionhero's tasks initialiser calling 'self.enqueue' with the correct parameters? Or am I wrong?

**Comment by evantahler** [comment]
The enqueue method handles many of the cases with fewer params.  This line applies here https://github.com/evantahler/actionhero/blob/master/initializers/tasks.js#L97.  We source the queue name from the task itself.
