### ISSUE TITLE
Try ioredis

### ISSUE THREAD

**Issue by evantahler** [evantahler/actionhero#665]
https://github.com/luin/ioredis

Is it really faster than `node-redis`?  It would be nice to use a single package that supports both sentinel and cluster, rather than have to inject the client.

**Comment by DefunctExodus** [comment]
Not sure if it is any faster but having one package the deals with sentinel/cluster  would be very nice.

**Comment by evantahler** [comment]
will be solved by https://github.com/evantahler/actionhero/pull/680
