### ISSUE TITLE
Integrating action hero with passport results in not saving user in req variable

### ISSUE THREAD

**Issue by Martinlck** [evantahler/actionhero#666]
Hello, I'm trying to use action hero with passport authentication, and I'm having an issue where I have to keep authenticating the user on every request even after it got authenticated because I cannot find the user data on the req variable. I followed up this gist example: https://gist.github.com/juancgarcia/e4caf5dc7474769f5137
Replacing all the old functionalities for the new ones since I'm using the new action hero version (like it has .addMiddleware instead of pushing to preProcessors array)
To give an example of my code I have separated my code into 3 different middlewares.
Auth, session, and passport. 
Just like the example states but I cannot seem to get it to work. Can someone please help me on this.
this is my auth middleware : https://gist.github.com/Martinlck/3ac3dab2f3d7ea68abc3
this is my passport middleware : https://gist.github.com/Martinlck/66492c989ac82ac307fe

**Comment by evantahler** [comment]
Sine this isn't an issue relating to actionhero itself (rather on how to use it with a specific library), I'm closing this issue. 

@neilstuartcraig has been working on a passport plugin for actionhero, he may be able to help you out.  He's got a chat room for his project: https://gitter.im/neilstuartcraig/ah-passport-plugin, and you can always jump into the normal actionhero room: https://gitter.im/evantahler/actionhero
