### ISSUE TITLE
actionhero REPL: string is not a function

### ISSUE THREAD

**Issue by justingosan** [evantahler/actionhero#667]
Hi!

Trying to run using `grunt console` in my existing project but I'm getting:
![](http://s3.jz10.info.s3-ap-northeast-1.amazonaws.com/monosnap/Monosnap_2015-08-01_23-12-03.png)
after I type in anything.

Also seems to fail when ran on new generated project using `actionhero generate`

I'm on Node 0.12.4 -- Yosemite
Any thoughts?

**Comment by evantahler** [comment]
Great catch!

That is fixed here https://github.com/evantahler/actionhero/commit/294a134c19d64bd6d01f259723ba93c4ca06c7a5

**Comment by justingosan** [comment]
Thanks for the quick fix!
