### ISSUE TITLE
recurring task runs before initializers

### ISSUE THREAD

**Issue by lorenzofox3** [evantahler/actionhero#669]
1) create a recurring task with high frequency (frequency property number low)
2) flush redis ```redis-cli flushall```
3) start actionhero

the recurring task runs for the first time before initializers has run causing errors as the task expects the database to be synced, etc.

**Comment by evantahler** [comment]
initializers have `start` and `load` priorities.  If you need to ensure that your database is connected before running tasks (totally makese sense), then make your database start priority lower than that of tasks, which happens to be [`900`](https://github.com/evantahler/actionhero/blob/master/initializers/tasks.js#L2)

**Comment by lorenzofox3** [comment]
Great, I did not know I could set the priority lower than the core components !
I am afraid there will still be some issues with plugins on which if I am not wrong I don't have the priority control (like ah-sequelize-plugin)

**Comment by evantahler** [comment]
very possibly... comment here! https://github.com/evantahler/ah-sequelize-plugin/issues/22
