### ISSUE TITLE
Actions throwing empty responses

### ISSUE THREAD

**Issue by fearhat** [evantahler/actionhero#672]
Hey,

we're currently using actionhero as an api-server (and mongodb for our data) and sometimes actions are sending empty responses (only server- and requesterinformation sent).

Example action:
```js
exports.action {
  name:                   'searchsuggestions',
  description:            '',
  blockedConnectionTypes: [],
  outputExample:          {},
  matchExtensionMimeType: false,
  version:                1.0,
  toDocument:             true,
  middleware:             [],
  mdl: true, // check for model name in route

  inputs: {
    q: {
      required: true
    }
  },

  run: function (api, data, next) {
    var splitted = data.params.q.split(' ');
    var query = [];

    splitted.forEach(function(qq) {
      var word = qq.stem();
      if(word.length > 0) query.push(new RegExp(escapeRegExp(word),'i'));
    })

    data.mdl.iClass.find({active: 1}).where('name').in(query).select('name').limit(10).lean().exec(function(err, classes) {
      if(err) next(err);
      else {
        classes.forEach(function(cl) {
          cl.distance = getEditDistance(data.params.q, cl.name);
        });

        var topFive = _.take(_.uniq(_.sortBy(classes,'distance'), 'name'), 5);

        data.response.result = topFive;

        next();
      }
    })
  }
}
```

data.mdl is just a wrapper for our mongoose schemas.

The api seems to work after live-editing the action file.
This is happening on ~10/30 actions randomly.
Is this a known issue with actionhero or did i mess up my code somewhere?

**Comment by fearhat** [comment]
seems to be related to #481 

What's the best way to force a param on (almost) all routes? We have a route param "mdl" which is required in 26/30 routes.
Right now it is done via a preprocessor in /initializers/file.js which checks the actionTemplate and then validates the "mdl" param.

**Comment by evantahler** [comment]
You've got a lot of logic in your MDL and your `_` reduction, any of which might be failing here silently.   What does `getEditDistance` do?  

If you also add `data.response.gotHere = true` or something right before the `next()`, you can at least confirm that actionhero is letting you append response data, and the error is coming from your logic above.

**Comment by fearhat** [comment]
Hey, thanks for the quick response!

getEditDistance is just returning the levenshtein distance for 2 strings (which is tested and actually working).

I have tried to set ```data.response.gotHere = true``` but the actual response is empty (again).

**Comment by fearhat** [comment]
So i think i've found the bug.
in my mdl middleware i check the actionTemplate:
```js
if(data.actionTemplate.mdl) {
  console.log("mdl required")
}
else {
  console.log("no mdl")
}
```

Even though my action has mdl set to true, it always logs "no mdl".

**Comment by evantahler** [comment]
haha, fair enough.

Good luck!
