### ISSUE TITLE
Note: ActionHero documentation

### ISSUE THREAD

**Issue by ifavo** [evantahler/actionhero#673]
Hey Evan!

I wanted to say thanks for creating such a beautiful project! I really love to use it and its just such a wonderful piece of software :-)

Because there are a lot of projects with ActionHero now, we did a small documentation helper which might be interesting for any other ActionHero users:
https://github.com/hpm/actiondoc

Can be tested here:
http://favo.s3.amazonaws.com/actiondoc/index.html#/

Cheers,
 Mario

**Comment by evantahler** [comment]
Neat! 

Be sure to mention this on the mailing list and gitter as well!
