### ISSUE TITLE
Recurring tasks can run before api is completely loaded

### ISSUE THREAD

**Issue by dangerdespain** [evantahler/actionhero#676]
I've got an issue where recurring tasks can start running before my database is fully connected and loaded with models (I'm using ah-sequelize-plugin). The model-loading portion of ah-sequelize-plugin happens in the initializer's start function (priority 1001) while AH's tasks initializer enqueues all recurrent jobs in its own start function at priority 900. 

This wasn't a problem before our API grew and our server load time increased. The server was usually able to load before resque picked up and ran the task. Now that this isn't always the case, I've got tasks locking up and crashing because the beginning of the Sequelize promise chain (the model) isn't defined. This is especially painful when expecting a Sequelize promise and the error handling chaining methods that it provides.

Looks like I'll be needing to change the start priority of either the tasks initializer or ah-sequelize-plugin initializer. I could fork but I'd rather fix the problem at the core. Actionhero ought to work with its own plugins without too much thought :) 

I would think that starting up tasks should be one of the last things that the server startup routine does. Is there a reason that the startPriority of the tasking initializer is 900 rather than 9999? If that's non-negotiable then perhaps a change to the plugin might be (I'll move the issue over there if that's the case)

**Comment by evantahler** [comment]
This should be fixed in ah-sequelize-plugin via https://github.com/evantahler/ah-sequelize-plugin/issues/22

**Comment by evantahler** [comment]
And if not, please comment on the plugin's page.

**Comment by dangerdespain** [comment]
Perfect! Thanks for the quick reply.
