### ISSUE TITLE
Conditional Get for static files

### ISSUE THREAD

**Issue by lorenzofox3** [evantahler/actionhero#681]
Although there is a basic support for cache control (with max-age) I think it would be very useful to support conditional get (with ETag for example), especially as the "must-revalidate" clause is added by default. 

I have tried to implement it but I have to admit: 
1- I get a bit confused with the callback chains, and where would be the best place to introduce the check and set the status code to 304. 
I think the check on the file freshness could be done [here](https://github.com/evantahler/actionhero/blob/master/initializers/staticFile.js#L22)
and the calculation of the Etag could be done [here](https://github.com/evantahler/actionhero/blob/master/servers/web.js#L106)
2 - while writing the spec, I don't see any straightforward way to access status code and request headers from the callback of api.specHelper.getStaticFile

Note 
- check on freshness of the file can be easily done with [fresh](https://www.npmjs.com/package/fresh)
- calculation of the etag can be done with [etag](https://www.npmjs.com/package/etag)

What do you think ?

**Comment by evantahler** [comment]
I'm happy to swap out the max-age header for an e-tag header.  It seems silly to do both.  

I would change things in the following way:
- [sendFile](https://github.com/evantahler/actionhero/blob/master/initializers/staticFile.js#L43) would calculate the etag and pass it on to the calling server, just like it does for the mime.  The staticFile initializer should not be responsible for HTTP actions, like response headers
- checking the old request etag header and changing the response status code is the responsibility of the web server, somewhere like [here](https://github.com/evantahler/actionhero/blob/master/servers/web.js#L387-L395).  You can run the staticFile methods, and they will only return a file stream (not the whole file), so there isn't much of a penalty if you decide that the body shouldn't actually be sent down to the user. 

I don't think you need `fresh` at all.  Always calculate the etag and just look at the old header and see if the new calculation matches.

**Comment by neilstuartcraig** [comment]
Hey guys. It'd be good to also have max-age for cache expiry - both CDN and browser. There's plenty of room for both :-)

**Comment by evantahler** [comment]
@neilstuartcraig good point!  I forgot that max-age takes priority over etag, and that would prevent the request entirely :D

A question for @lorenzofox3: I was under the impression that etag and "Last-Modified" are functionally equivalent options (just one uses an "asset sha" while the other would be using a date).  Since we really are serving files on disk (and not generating assets dynamically with the statidFile engine), wouldn't `fs.stat`-ing the file, and getting the true `last-modified` time form disk be simpler and quicker?  No new packages would be needed...

**Comment by lorenzofox3** [comment]
If I understand correctly the specifications:
-Etag is a hash of the content and you are right is more relevant when the content is generated dynamically ie by fetching data from a database and compiling in a document. Actually in AH, it would be more useful for the action part (and REST API for example), but this can be done with a middleware with no extra work on the framework.
- `last-modified` would be more appropriate for static files as you said

As @neilstuartcraig said, max-age remains relevant (it avoid any request to the server altogether) and I don't think it should be dropped.

I was suggesting fresh as it is very robust, light and support both (Etag and last modified): it is used in popular web frameworks express and Koa. That would be code not to maintain on AH side, but if you prefer to roll you own solution is fine too.

I'll make the pull request this week end if you want, according to your instructions

**Comment by neilstuartcraig** [comment]
I have a module (which I don't like the organisation of st the moment and might be a little out of date) which has the main aim to provide a caching AH client for the browser (which works pretty well). It does sone header management for http and also websockets. It should have most of the code you want. https://github.com/neilstuartcraig/ah-tdp-js-connector-plugin

Might safe a little time?

I was aiming to split out the header management stuff into a separate module. I'd like to be able to eg set headers for http and pseudo headers for websockets by just amending an object in AH which would have defaults. 

Anyway, I'll stop rambling now :-)

**Comment by evantahler** [comment]
closed by https://github.com/evantahler/actionhero/pull/685
