### ISSUE TITLE
ActionHero and PM2

### ISSUE THREAD

**Issue by kodypeterson** [evantahler/actionhero#684]
It seems ActionHero and PM2 don't play well together. This makes it tough to integrate into CI/CD environments and scripts.

I am going to start looking into this, but was not sure if you had any past investigation info about this or are unaware.

**Comment by evantahler** [comment]
There has been a lot of chatter about pm2 in the [actionhero chat room](https://gitter.im/evantahler/actionhero) in the past 2 months.  A lot of people don't use it any more (stability reasons I think?), and have started using `actionCluster` directly.  Running a single actionhero server `./node_modules/.bin/actionhero` should be fine though.

@crrobinson14 has had the most experience, and even offered up his config:

````
[{
    "name"       : "API",
    "cwd"        : "/opt/firetalk/api",
    "script"     : "/opt/firetalk/api/node_modules/.bin/actionhero",
    "args"       : "startCluster",
    "watch"      : false,
    "env"        : {
      "NODE_ENV" : "production",
      "ACTIONHERO_CONFIG" : "config,local-config",
      "ACTIONHERO_ROOT"    : "/opt/firetalk/api/node_modules/actionhero",
      "HTTP_PORT": 8080
    },
    "instances"  : "1",
    "error_file" : "/var/log/pm2/api.err",
    "out_file"   : "/var/log/pm2/api.out",
    "pid_file"   : "/var/log/pm2/api.pid",
    "exec_mode"  : "fork_mode"
}]
```

**Comment by crrobinson14** [comment]
Yes, we used it here to manage AH for firetalk.com. I'm a big fan of it, but we just couldn't get its CPU usage to be consistent. It's a problem that's been reported and solved several time for several different reasons just in the past year we've used PM2, and we just couldn't run it any more. We still use it on QA boxes where we don't need clustered operation but everywhere else we've converted to foreverjs.

However, the config above does work very well for us and we do have boxes still running it. I don't know what "don't play well together means" but we use Jenkins to rebuild on every git commit/push and PM2 worked very well restarting ActionHero reliably.

**Comment by kodypeterson** [comment]
@crrobinson14 @evantahler Thanks for the config. I am going to see the difference I have in my config. Maybe that is the issue. I just notice when we have travis run pm2 restart it is not always returning the status code in order to have travis complete the build. It also might be something up with our ssh script or something silly. Still want to look into it as even running pm2 restart on the box does not always do as expected, but only with actionhero.

**Comment by crrobinson14** [comment]
@kodypeterson I'm guessing that's what it is. Our staging server deployment script was nothing more than:

ssh root@STAGING "cd /opt/app && git pull && npm install && pm2 restart WWW"

Note that pm2 is sensitive to user permissions/rights. Any user can use it to restart a service - but only if they have read/write access to the .pm2 folder! This is created by default in the home directory of the first user who runs it and causes trouble for all others, especially if you go between root and non-root. You can move it with an environment variable... but you have to be careful to avoid getting two "God daemons", which happens for the slightest mistake. Heaven forbid you need to change the environment variables of the process. You basically need to delete and re-create it.

This was one of the reasons we dropped it for foreverjs. Forever isn't quite as feature-rich but it's much more forgiving.

I would suggest that none of this actually has anything to do with ActionHero - you might want to confirm back to Evan so he can close the ticket.

**Comment by evantahler** [comment]
closing due to lack of response

**Comment by crrobinson14** [comment]
Update for posterity (not re-opening, this is just comment/doc). We have now switched away even from foreverjs to using Supervisor. Although this is a Python tool it's a REALLY well made application, very easy to use, and it hits all our NodeJS buttons as well as those for other languages as well.

Here's a sample config - note that you can include a "stop signal" that ties to TERM/USR2/etc. to allow ActionHero to do friendly-restart actions. This is very important when running a task processing node to let AH clean up its workers being stopped.

    [program:myapp]
    command=/opt/myapp/api/node_modules/.bin/actionhero startCluster
    directory=/opt/myapp/api
    environment=NODE_ENV="production",ACTIONHERO_CONFIG="config,local-config"
    autostart=true
    autorestart=true
    stopsignal=TERM
    stderr_logfile=/var/log/myapp.err.log
    stdout_logfile=/var/log/myapp.out.log

**Comment by l0oky** [comment]
Hmm, thanks for sharing @crrobinson14 - I wonder what features does it have that makes It better then PM2.

**Comment by evantahler** [comment]
And I always use [monit](https://mmonit.com/monit/)!  I find it is the best combination of both control and monitoring (and with M/monit, you get central control of all your servers...)

Here's my config.  This is the "fancy" version, but you don't need it all (I've also got some hooks into alerting pagerDuty for high CPU, RAM, etc which you can see:

```
CHECK PROCESS actionheroApp
  
  WITH PIDFILE /home/user/www/actionheroApp/shared/pids/cluster_pidfile
  
  START PROGRAM "/bin/bash -c 'cd /home/user}/www/actionheroApp/current && HOME=/home/user PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH NODE_ENV=production ./node_modules/.bin/actionhero startCluster --daemon --workers=10'"
    as uid user
    with timeout 30 seconds
  
  STOP PROGRAM "/bin/bash -c 'kill `cat /home/user}/www/actionheroApp/shared/pids/cluster_pidfile`'" 
    as uid user
  
  GROUP apps

  if mem is greater than 600 MB for 5 cycles 
    then exec "/bin/bash -c 'kill -s USR2 cat `cat /home/user/www/actionheroApp/shared/pids/cluster_pidfile`'"

  if totalmemory is greater than 800 MB for 10 cycles 
    then exec "/bin/bash -c 'kill -s USR2 cat `cat /home/user/www/actionheroApp/shared/pids/cluster_pidfile`'"

  if mem is greater than 600 MB for 5 cycles 
    then exec "/etc/monit/pagerduty-trigger actionhero_actionheroApp_ram"
  else if passed for 3 cycles
    then exec "/etc/monit/pagerduty-resolve actionhero_actionheroApp_ram"

  if totalmemory is greater than 800 MB for 10 cycles 
    then exec "/etc/monit/pagerduty-trigger actionhero_actionheroApp_ram"
  else if passed for 3 cycles
    then exec "/etc/monit/pagerduty-resolve actionhero_actionheroApp_ram"

  if cpu is greater than 25% for 20 cycles 
    then exec "/etc/monit/pagerduty-trigger actionhero_actionheroApp_cpu"
  else if passed for 3 cycles
    then exec "/etc/monit/pagerduty-resolve actionhero_actionheroApp_cpu"

  if totalcpu is greater than 90% for 10 cycles 
    then exec "/etc/monit/pagerduty-trigger actionhero_actionheroApp_cpu"
  else if passed for 3 cycles
    then exec "/etc/monit/pagerduty-resolve actionhero_actionheroApp_cpu"

  if uptime < 1 minutes for 3 cycles
    then exec "/etc/monit/pagerduty-trigger actionhero_actionheroApp"
  else if passed for 3 cycles
    then exec "/etc/monit/pagerduty-resolve actionhero_actionheroApp"
```
