### ISSUE TITLE
Altering date of delayed task

### ISSUE THREAD

**Issue by mstdokumaci** [evantahler/actionhero#688]
This is a feature request related to resque.

Sometimes I enqueue a delayed task and later I need to postpone or advance it several times. I call 2 different methods to do it.

```js
api.tasks.delDelayed('default', 'task_name', {param1: param}, function () {
	api.tasks.enqueueAt(
		new_date, 'task_name',
		{param1: param}, 'default',
		next
	)
});
```

I guess this way I cause several redis calls in the background. Just for sake of optimisation, might we have a single method for altering timestamp of an already enqueued delayed task? For example:

```js
api.tasks.alterDelayed('default', 'task_name', {param1: param}, new_date, next);
```

**Comment by evantahler** [comment]
Either way, you would still need to call redis multiple times (the logic can't be changed).  If you really want this convince method, open up a PR in https://github.com/taskrabbit/node-resque!  Once it's merged in there, we'll add it to actionero
