### ISSUE TITLE
FakeRedis package broken

### ISSUE THREAD

**Issue by liorhson** [evantahler/actionhero#690]
Hello,
I'm starting to get the following error while using Actionhero, even when I'm starting a new application with the "generate" command

```
info: actionhero >> start
2015-10-18 16:27:00 - notice: *** starting actionhero ***
2015-10-18 16:27:00 - warning: running with fakeredis
undefined:1
undefined
^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at new RedisClient (/Users/lior/work/actionhero/node_modules/actionhero/node_modules/fakeredis/node_modules/redis/index.js:39:20)
    at Object.exports.createClient (/Users/lior/work/actionhero/node_modules/actionhero/node_modules/fakeredis/main.js:34:12)
    at Object.api.redis.initialize (/Users/lior/work/actionhero/node_modules/actionhero/initializers/redis.js:28:45)
    at Object.module.exports.initialize (/Users/lior/work/actionhero/node_modules/actionhero/initializers/redis.js:183:15)
    at loadFunction (/Users/lior/work/actionhero/node_modules/actionhero/actionhero.js:108:44)
    at /Users/lior/work/actionhero/node_modules/actionhero/node_modules/async/lib/async.js:689:13
    at iterate (/Users/lior/work/actionhero/node_modules/actionhero/node_modules/async/lib/async.js:265:13)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! my_actionhero_project@0.0.1 start: `actionhero start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my_actionhero_project@0.0.1 start script 'actionhero start'.
npm ERR! This is most likely a problem with the my_actionhero_project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     actionhero start
npm ERR! You can get their info via:
npm ERR!     npm owner ls my_actionhero_project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lior/work/actionhero/npm-debug.log
liors-MacBook-Pro:actionhero lior$ node -v
v0.12.6
```

Do you have any idea?

**Comment by ifavo** [comment]
This is an issue with fakeredis and how it includes the RedisClient. I didn't dive deep enough to find the real problem but if you have a redis instance, using it should get you started again.

**Comment by liorhson** [comment]
Hey,
fakeredis is good for me to handle in memory cache such as Session. 
The framework is actually broking, even when you try to start vanilla version of Actionhero it doesn't start

```
npm install actionhero
./node_modules/.bin/actionhero generate
npm start
```

**Comment by evantahler** [comment]
It looks like a recent upgrade of `redis` (which `fakeredis` depends on) changed some of its internals.  This means that all new installs of `fakeredis` are failing.

Issue opened with the fakeredis project  https://github.com/hdachev/fakeredis/issues/31

Thanks for pointing this out!

**Comment by liorhson** [comment]
Thanks,
Can you give me a workaround for know, we are using Actionhero in one off our products

**Comment by evantahler** [comment]
You have a few options:
1) use "real" redis.  Install a redis server and connect to it
2) fork the fake redis package and lock it's dependency to `redis: 2.1.x`.  use your fork of rake redis from github rather than the one from NPM

**Comment by evantahler** [comment]
@hdachev is awesome has a new version of fakeredis published

**Comment by evantahler** [comment]
solved by https://github.com/evantahler/actionhero/commit/686dee3379b0240526db6f56b43245ad3b63cc29

**Comment by evantahler** [comment]
v12.1.2: published

**Comment by liorhson** [comment]
Thanks for the quick response!

**Comment by hdachev** [comment]
np, my bad! wasn't really responsible with the deps
