### ISSUE TITLE
actionheroClient.js not purging old websocket connections

### ISSUE THREAD

**Issue by ccapo** [evantahler/actionhero#696]
I'm having an issue with web-socket connections to actionhero, in particular when I try to connect and disconnect to the web-socket server multiple times in the same browser session, the total number of web-socket connections increases with each connection. Even though I use the actionheroClient.disconnect command to sever the connections, each time I connect all the previous web-socket connections are re-established along with the new connection. I've experienced this with actionhero v12+ using redis-server v3.0.5 on Ubuntu 14.04. I'd appreciate any help, and if you need any more details about my setup, please let me know.

**Comment by evantahler** [comment]
good catch!   Will be solved by https://github.com/evantahler/actionhero/pull/697

I guess no one has manually tried to disconnect and reconnect in the same window before

**Comment by ccapo** [comment]
Glad I could help, but I'd like to thank you for the rapid response and for creating such a fantastic product!
