### ISSUE TITLE
sendFile 

### ISSUE THREAD

**Issue by ifavo** [evantahler/actionhero#698]
Hi!

From time to time I'm delivering some static files with actionhero and always run into trouble.
Files are not fully sent before the connection closes because the call of next(false) closes the connection and does not wait until the file is piped to the client. In addition the sendFile function does not support a callback when the file has been sent, which prohibits me from calling the next-callback in my action when everythings done. I worked around this by not calling the next-callback in my actions (or with a very long delay).

I've looked around in the server files and found the following issues:

https://github.com/evantahler/actionhero/blob/de74425c3cf5966b1b164221772a1640f5063146/servers/web.js#l146-l148

    connection.rawConnection.res.on('end', function(){ 
      connection.destroy(); 
    });

This should be called when a file has been pipe to the client but I never see it being called in my environments (node 0.10.37, latest actionhero).

As a fix for me I added the following listener within my actions (only works on the web-server):

                            data.connection.rawConnection.res.on('finish', function() {
                                next(false)
                            });

… listening to the finish event informs me right when the file has been sent and allows me to continue running some more code – or call the next()-callback. So I guess the event-listener in the web-server is not correct and should maybe changed to the finish event.

While poking around there I also wanted to see if it is easy to add a callback function in the servers core, which is called whenever the file has been piped to the user. From what I see,  this is currently not supported.

I would still like to add this. What would be the best approach? Simply going the easy way by passing a callback function thru the dozens of functions that are called while sending a file? Or using some event listener and call it very early? (like on the finish event) (I prefer the latter)

Cheers,
 Mario

**Comment by evantahler** [comment]
If you are trying to send static files from within actions, all you need to do is:

```javascript  
exports.bigFile = {
  name: 'bigFile',
  description: 'I will return a big file',
   
  outputExample:{},

  run: function(api, data, next){    
    data.connection.sendFile('/path/to/file.mp3');
    data.toRender = false;
    next();
  }
};
```

Calling `next(false)` indicates that there was an error, and as you point out, would both try to render the error to the client, and send the file.  The only error that should mater when sending files is 404, and that is handled automatically via `sendFile`

**Comment by evantahler** [comment]
The docs were out of data, and I've updated them https://github.com/evantahler/actionhero/commit/2aed6145a4d88374125c69adec594b85906287db
