### ISSUE TITLE
help not related to actionhero

### ISSUE THREAD

**Issue by SiddiqueAhmad** [evantahler/actionhero#699]
i just saw that our actionhero redis showing following

Db0	keys=815598,expires=0

is there a way to delete expired keys

**Comment by evantahler** [comment]
There is a `redis-cli` command which lets you use any of the [`redis-commands`](http://redis.io/commands).

You can delete all keys in a DB with `flushdb` or you can list keys `keys *` and then `del [key]` one by one.
