### ISSUE TITLE
README links need to be updated

### ISSUE THREAD

**Issue by crazy4groovy** [evantahler/actionhero#707]
Eg. wrong: http://actionherojs.com/docs/ops/getting-started.html --> correct: http://www.actionherojs.com/docs/#getting-started

**Comment by evantahler** [comment]
duplicate of https://github.com/evantahler/actionhero/pull/706/

**Comment by slattery** [comment]
Hmmm, the README.md needs work too, new PR incoming, sorry about the gh-pages mixup last time...

**Comment by evantahler** [comment]
solved by https://github.com/evantahler/actionhero/pull/710
