### ISSUE TITLE
Support HTML control-name arrays

### ISSUE THREAD

**Issue by AngeloR** [evantahler/actionhero#709]
Right now as per HTML spec, the control-name attribute in forms can support multiple elements having the same name (http://www.w3.org/TR/html401/interact/forms.html#control-name). It has become convention to perform the following in forms:

```html
<form>
  <input type="checkbox" name="topping[]" value="mushrooms">
  <input type="checkbox" name="topping[]" value="pineapples">
</form>
```

On submission, the corresponding form-data is sent
```
topping%5B%5D=mushrooms&topping%5B%5D=pineapples
```

Currently, up until here, things are supported just fine. However, instead of using the "topping" input name that you would expect in most other frameworks/languages, actionhero forces the "topping[]" name. While, yes, technically the "topping[]" control-name is correct, does it not make more sense to be able to define "topping" as an input?

Current: 
```js
exports.action = {
...
  inputs: {
    "topping[]": {required: true}
  }
}
```

Proposed:
```js
exports.action = {
...
  inputs: {
    "topping": {required: true}
  }
}
```

It is a very small change from a users perspective, but puts using this functionality in line with other frameworks.

**Comment by evantahler** [comment]
Just linking some of the previous conversations on the topic of 'complex params' here for reference: 
- https://github.com/evantahler/actionhero/issues/649
- https://github.com/evantahler/actionhero/issues/314

**Comment by evantahler** [comment]
I think that at this point I'm generally OK coercing and merging params which end with `[]` into an array (as you point out in your example).  

- Should we also handle nested params: `pizzaType[topping][]` => `params.pizzaType = {topping: []}`, or just handle the simple case?
- do you want to work on this feature, or is this just an ask?

**Comment by AngeloR** [comment]
After testing a few different libraries it looks like

- HapiJS supports it
- Restify does not support it
- Express supports it through the new express body parser, which is actually reliant on the core Hapijs QS parser

I think if it is going to be implemented, the simple case outlined above can be integrated into the core. The more complex scenarios are a much more opinionated change and there is really no spec for it. I think it is best provided as middleware, as you suggested in #314. This way actionhero is free to define how to define input params in the action definition. I believe this is really the hard part and what is up for discussion. 

The way @joseym suggested works, but perhaps an extension as follows

```js
{
 inputs: {
    required: [
       { 'amount': {formatter: ..., validator: ...}}
      , 'contact.purchaser.name'
      , {'contact.purchaser.email': {formatter: ..., validator: ...}}
      , 'contact.purchaser.address.line_1'
      , 'contact.purchaser.address.city'
      , 'contact.purchaser.address.state'
      , 'contact.purchaser.address.postal'
    ],
    optional: [
        'contact.purchaser.phone'
        'contact.purchaser.address.line_2'
    ]
  }
}
```

If you're open to it, I wouldn't mind digging into these myself. Are there contribution guidelines somewhere?

**Comment by evantahler** [comment]
Lets move over to https://github.com/evantahler/actionhero/pull/711
