### ISSUE TITLE
Action input formatter is not behaving as It should.

### ISSUE THREAD

**Issue by l0oky** [evantahler/actionhero#717]
This is a relatively simple task I want my action to do. Action should format my input - that is convert stringified JSON to object. 

Here's a [gist](https://gist.github.com/l0oky/b15745575112513fa691) of the code that is not calling `action.run` after using formatter and a workaround I did. No middlewares are used. *Lodash* is also not used.

Formatter in the [non-working code](https://gist.github.com/l0oky/b15745575112513fa691#file-not_working_action-js-L34) should at least give me some errors If It decides not to call `action.run`.

**Comment by evantahler** [comment]
Share some example input in the form of a curl statement.  This all woks fine for me.

It's strange that you are trying to JSON.parse in both cases, formatter and validator.  Also, in line 41 you are setting param to the literal string `Product must be a JSON object.`, which I don't think is what you intended

**Comment by l0oky** [comment]
Action with and without formatter gave the same result for you?

My goal was to allow input of stringified type and of normal object like this:
```bash
# {"name":"test","version":"1.0.0"}
curl -d 'product={"name":"test","version":"1.0.0"}' 'http://127.0.0.1:8080/api/addProduct'

# "{\"name\":\"test\",\"version\":\"1.0.0\"}"
curl -d 'product="{\"name\":\"test\",\"version\":\"1.0.0\"}"' 'http://127.0.0.1:8080/api/addProduct'


# ( product is represented as a JSON with canonical notation )
```

```javascript
formatter: function(param, connection, actionTemplate){
 if(typeof param === 'string'){  // If product input is string ( "{\"name\":\"test\",\"version\":\"1.0.0\"}" ) then parse it.
        try{ 
            return JSON.parse(param);
          }catch(e){
            return 'Product must be a JSON object.';
          }
 }
 return param; // If It's not a string just return it as it is ( as it will be object )
});
```

Also I am using `JSON.parse();` in validator because It's the only way to check If JSON is valid.
Thanks for your response!

**Comment by l0oky** [comment]
OK, I really feel bad for taking your time now because I got this to work. 
The real issue is that I remained ignorant on what does formatter really do.
So [here's the working version](https://gist.github.com/l0oky/64209f8cb338f69a464a).

Sorry for taking for precious time, and thanks for all your help!

**Comment by evantahler** [comment]
No problem!  Happy you figured it out.
