### ISSUE TITLE
Improvement/Question - Configurable task logging level

### ISSUE THREAD

**Issue by dangerdespain** [evantahler/actionhero#719]
My console is starting to get noisy with all of the recurring tasks my latest project has running. Literally dozens of lines logged similar to this 
`2015-12-16 14:34:42 - info: worker: job success default workerId=1, class=schedulePosts, queue=default, result=null
` per minute.

I'd like to set up an option in api.config.tasks to set the logging level for tasks. Something like `api.config.tasks.loggingLevel = 'debug'` Would this be a welcome pull request?

**Comment by evantahler** [comment]
Sure! 
Maybe we allow for log levels for each task event that you can customize, like:

```js
api.config.tasks.logLevels.tasks = {
  start: 'info',
  success: 'debug',
  failure: 'error',
  // ...
};

api.config.tasks.logLevels.scheduler = {};
```

This should also replace `api.config.tasks.verbose`

**Comment by dangerdespain** [comment]
Love it! :+1:

**Comment by dangerdespain** [comment]
Alright, details are in the pull request. As always, I'm open to input or tweaks!
