### ISSUE TITLE
Deploy actioncluster clarification 

### ISSUE THREAD

**Issue by NizarBlond** [evantahler/actionhero#721]
Hi,

The objective is getting practical answers that explain how to run "Workers" in parallel that listen to a certain queue (e.g. redis) in an actionCluster.

As far as I understand the flow, is as follows:

<b>"Web"-node</b>

A "web"-node is required for manipulating the queue (insert/remove input) and show results (e.g. read from MongoDB) on dashboard.

In actionhero words: "web"-nodes run actions (restful api), which enqueue jobs (e.g. to Redis). 

Another server in the cluster, that isn't "web"-node but "worker"-node that runs time consuming tasks, will be listening to Redis and get the enqueued job. 

Questions:

1) How to deploy this actionCluster that includes "web" and "worker" nodes?

2) Practically, how do I start a node js process (worker) in actionhero, instead of the default "web"? npm start will probably start a "web"-node, but that's not what I want, I want to start the process as "worker"-node, where in the configuration it does make the difference and how do I start it?

3) How do workers listen to jobs in the redis queue? Do they run in an infinite loop (e.g. something similar to http listener) or there are better ways (e.g. scheduling)? In other words; what makes a "worker" get to know that there is a task waiting for it?

I would be grateful to you if you provide practical details, such as code samples and actionhero CLI commands.

Cheers

**Comment by evantahler** [comment]
There are new docs about this here: http://www.actionherojs.com/docs/#topology-example with code examples

1) `actionCluster` can only start one type of node.  Say you had a 4-CPU server.  You could use actionCluster to start a manager and 2 web nodes, and then start 2 more workers in a new actionCluster (see below).  Note that using ENV flags at boot requires you to update your config files (as noted in the documentation) to read those flags, IE: `if(process.env.ACTIONHERO_ROLE === 'worker')`.

- start the cluster with 2 web workers:
  - `ACTIONHERO_ROLE='server'  ./node_modules/.bin/actionhero startCluster --workers=2 --daemon`
- start 2 workers:
  - `ACTIONHERO_ROLE='worker' ./node_modules/.bin/actionhero startCluster --workers=2 --daemon`  

2) All we are changing here is config settings!  Use boot flags to modify config settings at runtime, or you can lay down new config files for each role (if you have separate servers for each type of node)

3) Yes, workers more or less run in an infinite loop, but then again, so does all of actionhero.  The worker logic can more or less be though of:

1. check for jobs
  - try to 'pop' a job off of an array in redis
2. if job, work job
  - goto 1
3. if no job, sleep 5
  - goto 1

To learn more about how the workers process jobs from redis, you can check out the [node-resque](https://github.com/taskrabbit/node-resque) package (which actionhero uses under the hood) or the original [ruby-resque](https://github.com/resque/resque)
