### ISSUE TITLE
Remove Domains

### ISSUE THREAD

**Issue by evantahler** [evantahler/actionhero#722]
Domains are deprecated.  We should remove them.

**Comment by l0oky** [comment]
Call me ignorant about domains. But what really are they in `actionhero`? Little is said about them in the documentation.

**Comment by hutchike** [comment]
This is domains: https://nodejs.org/api/domain.html

They're used in a few places in ActionHero code, e.g. initializers/actionProcessor.js

**Comment by evantahler** [comment]
solved by https://github.com/evantahler/actionhero/pull/737
