### ISSUE TITLE
question of JSON payload and URL parameters

### ISSUE THREAD

**Issue by ymote** [evantahler/actionhero#724]
Hi There,

After reading how to parse the JSON form payload and URL parameters I am still confused how to do it with the latest release.
The questions are
1. Is possible to parse the URL parameters with the JSON payload form parameter in the same time? It would be so much convenience if both parameters can be parsed.

2. If so how to write the input for URL parameters and the JSON payload?

3. If not, what it the right way to write the JSON payload form parameter parser in the action with the latest release?

Thanks so much!

Here is the example
`curl -v -H "Content-Type: application/json" -X POST -d 'score={"who":"some_one", "score":"92"}' http://localhost:8080/api/score/user/tom`

Here is the route.js config for the POST action
```
post: [
       { path: '/score/user/:user', action: 'createScore' }
      ]
```

How to write the input parser in the action? I did not get it work
```
  inputs: {
    user: {
      required: true,
      formatter: function(s){ return String(s); }
    },
      score: {
      required: ['payload'],
    },
  },
```

**Comment by evantahler** [comment]
First off, `required` is a boolean, `true` or `false`.  

If this is your action 
```js
exports.test = {
  name: 'test',
  description: 'test',

  inputs: {
    data: {
      required: true,
      formatter: function(n){
        return JSON.parse(n)
      },
    }
  },

  outputExample: {},

  run: function(api, data, next){
    api.log('data => ', 'alert', data.params.data)
    data.connection.response = 'yay';
    next();
  }
};
```

(note how JSON.parse is used)

You can send params:

`curl -v -X POST -d 'data={"who":"some_one", "score":92}' http://localhost:8080/api/test`.  The default content-type from CURL (and browsers) is `application/x-www-form-urlencoded`, which actionhero expects. 

If you want to change the request content type to `application/json`, you actually don't use URL-style params, and should CURL like this: `curl -v -H "Content-Type: application/json" -X POST -d '{"data":"some_one"}' http://localhost:8080/api/test` (note that there is no assignment for the payload, it's the only data param).

If this is how you want to interact with the API, you don't need to JSON parse in your action, as JSON like this will automatically be parsed to set `data.params.data = 'some_one`.  That means your action changes to:

```js
exports.test = {
  name: 'test',
  description: 'test',

  inputs: {
    data: {
      required: true,
      formatter: function(n){
        return String(n)
      },
    }
  },

  outputExample: {},

  run: function(api, data, next){
    api.log('data => ', 'alert', data.params.data)
    data.connection.response = 'yay';
    next();
  }
};

```

**Comment by ymote** [comment]
Both way works for me. Thanks so much.
