### ISSUE TITLE
Multi-pathPart URL matchers for routes

### ISSUE THREAD

**Issue by evantahler** [evantahler/actionhero#725]
Right now, you cannot match more than one `pathParth` in the router.  That means you are restricted in matching formal RESTful path sections (what you are matching cannot contain a `/`).  

Let's add an option to the router which allows the current path part to match *all following* path parts, which would rejoin them with a `/`, which can then be matched against.  This would be the second param defined in the route matcher object.

For example:
```javascript
post: [
  // yes match: site.com/api/123
  // no match: site.com/api/123/admin
  { path: '/login/:userId(/.*/)', action: 'login' }
],

post: [
  // yes match: site.com/api/123
  // yes match: site.com/api/123/admin
  { path: '/login/:userId(/.*/)', action: 'login', matchTrailingPathParts: true }
],
```

This would also (finally!) allow you to define a single action for **all** routes as a catch-all

**Comment by evantahler** [comment]
solved by https://github.com/evantahler/actionhero/pull/728

**Comment by slattery** [comment]
Nice!  I have a plugin that could use a catchall, for two reasons. 

I set up a quick testing plugin that would take any action request that had a production plugin's action name and return test content instead.   

The test plugin would either return test data when the test plugin had a corresponding action in its own actions folder,  or return the output_sample from the production plugin's action if the name matched a production action but had no corresponding test action of its own.   

Without a catchall, how would we account for changes in the production action array, and catch all the production actions that had no test counterpart? 

Without a catch-all, I run an initializer every start.   For each production action that had no corresponding action in the test plugin, I generate a test action that returns the production twin's output_sample.   

To allow API consumers to address the test actions with a single consistent switch, I register the test actions with the same name as production and set the API version to zero.    This way each call just needs to add the API version in all requests to get test content.

Having a catchall route near the root for the test plugin might be better or more polite than using API versioning there.   As a bonus I could pair a test action with a production action on the fly if none is found in the actions folder.

So thanks!!!

**Comment by evantahler** [comment]
Check out the PR and let me know if that works for you.
