### ISSUE TITLE
Support for Nested Plugins

### ISSUE THREAD

**Issue by evantahler** [evantahler/actionhero#726]
...?

**Comment by l0oky** [comment]
Yes! What If an actionhero plugin needs another actionhero plugin? A solution like this would be awesome. +1

**Comment by l0oky** [comment]
When I think of it a bit more, nested plugins probably have the same agenda as [plugin auto-registration](https://github.com/evantahler/actionhero/issues/727).. Am I right?

**Comment by hutchike** [comment]
Just wanted to point out that NPM has been doing this job rather well for quite a while now. It might make sense to leverage NPM by requiring "actionhero-plugin" in your plugin, obeying some design pattern, then publishing your plugin as a module to NPM? Just my 2c.

**Comment by l0oky** [comment]
Yes. Using NPM for this is a must.

**Comment by neilstuartcraig** [comment]
This (using npm) is what I do, personally. I tend to create a wrapper for my project which had all the deps as npm requirements and has a runnable installer which does the ah generate and any other custom install tasks. It works very well.

**Comment by l0oky** [comment]
Plugins should also have the ability to set the minimum actionhero version required in `packages.json`. I guess that means having actionhero in `node_modules` directory. That can come in handy.

**Comment by evantahler** [comment]
Cool.  Closing this issue in favor of this PR https://github.com/evantahler/actionhero/pull/758.
Move the conversation over there!
