### ISSUE TITLE
Routing question

### ISSUE THREAD

**Issue by running-coder** [evantahler/actionhero#729]
Hey, I've just start installing & doing tests with your project and so far this is just amazing... gj

regarding my question, I was playing with routing variants and found something that may not work or perhaps I wrote it wrong, here is the issue:

``` javascript
// Route inside /config/routes.js (GET)
{ path: '/:apiVersion/randomNumber/min/:min/max/:max', action: 'randomNumber' }

// Works
http://127.0.0.1:8080/api?action=randomNumber&min=1&max=10&apiVersion=v1

// Works, pointing to v2 (min and max are optionals required:false by default)
http://127.0.0.1:8080/api?action=randomNumber&min=1&max=10
http://127.0.0.1:8080/api?action=randomNumber

// Works using "folder path" structure
http://127.0.0.1:8080/api/randomNumber
http://127.0.0.1:8080/api/v2/randomNumber/min/10/max/20

// Doesn't work
http://127.0.0.1:8080/api/v2/randomNumber
// info: [ action @ web ] to=127.0.0.1, action=undefined, params={}, duration=0, error=Error: unknown action or invalid apiVersion

// Doesn't work unless I add another route without "/:apiVersion" at the start
// In the doc it says that this param is treated as optional
http://127.0.0.1:8080/api/randomNumber/min/10/max/20

```

Thanks

**Comment by evantahler** [comment]
Yep, that's working as designed.  If you define your route to have a param, it must be there to match!  

`:apiVersion` being optional only applies to the fact that clients don't need to supply it, and if they don't the latest version will be used.  This optionality goes away however if you require it in your route.

**Comment by running-coder** [comment]
Ah! my first toughts were that ``http://127.0.0.1:8080/api/v1/randomNumber/`` (doesn't work) would be the equivalent to ``http://127.0.0.1:8080/api?action=randomNumber&apiVersion=v1`` (works). Also reading the documentation @ http://www.actionherojs.com/docs/#inputs, I tought that the params wouldn't need to be there if working with "folder structure" urls. My bad perhaps I missunderstood that part

Thanks for the fast answer!
