### ISSUE TITLE
undeclared 'next' && hardcoded log path

### ISSUE THREAD

**Issue by synthmeat** [evantahler/actionhero#741]
https://github.com/evantahler/actionhero/blob/master/config/logger.js#L24

**Comment by l0oky** [comment]
next() is a configLoader thing.. means this config script is over with parameters.

**Comment by synthmeat** [comment]
Well, it crashes with undefined ```next``` if I force it to go to catch block in some way.

**Comment by synthmeat** [comment]
Updated issue title because it's another related issue in the same block - log path is hardcoded in ```try```, but we already have it in ```config/api.js```. Template as well as source.

**Comment by evantahler** [comment]
good catch! 
Solved via https://github.com/evantahler/actionhero/pull/745

Looks like it has been this way for almost a year... I guess that means no one has tried to change the log path until now...
