### ISSUE TITLE
General plugin postInstall issue

### ISSUE THREAD

**Issue by synthmeat** [evantahler/actionhero#755]
If one can configure config location in ```api.js```, then plugins should account for that and not error out on their postInstalls, where they have particular expectation of directory structure.

My personal preference would be just that they respect ACTIONHERO_CONFIG environment variable, as the core actionhero does.

The fix would be fairly trivial, but it should be across the whole range of ah plugins.

**Comment by evantahler** [comment]
Cool.  
There's a [big rewrite of how plugins work](https://github.com/evantahler/actionhero/pull/758) going on right now, but this will get fixed as part of that.

Specifically: https://github.com/evantahler/actionhero/commit/5b837dec00b9934f91361af06baaeb3f0fe0a63e

**Comment by evantahler** [comment]
Oh yeah... there should be no more "postinstall" scripts at all after the update.
