### ISSUE TITLE
Feature: Autoloading nested plugins

### ISSUE THREAD

**Issue by evantahler** [evantahler/actionhero#766]
I left this as "TODO" in the [v13](https://github.com/evantahler/actionhero/releases/tag/v13.0.0) release, as we can address this now without a major version bump (this would become `v13.1.0` or something like that). 

Basically, you can have `.link` files in your plugins, for sure, and modules they would link would get loaded. If all the plugins needed are at the top level (meaning explicit dependancies in your `package.json`), everything works. However, we don't source the node_modules of plugins yet, because the user didn't list that as a valid/safe `api.config.general.paths.plugin` location. So if your plugin includes another plugin which the top-level package did not also include, it won't work.

This is a security issue we need to sort out.

**Comment by evantahler** [comment]
For example:

I trust "my" `node_modules` to load plugins from, but I don't trust `node_modules/random_plugin/node_modules`... who knows whats in there?!

Right now (`v13.0.0`), you can chain things in your plugins path, ie
`api.config.general.paths.plugins = ['node_modules', 'node_modules/somePlugin/node_modules']`
but it won't auto load that way.

You also can't append `api.config.general.paths.plugins` in an initializer within your plugin, as the directory list should already be sourced.

**Comment by l0oky** [comment]
So in one example scenario, I want to install a explugin that depends on subplugin. Subplugin is not installed on top-level project. When I want to install explugin 'npm install ah-ex-plugin' npm should also install subplugin and source it in 'package.json' ?

**Comment by evantahler** [comment]
@l0oky that's the way it is now, yes.  I want to talk here about alternative options...

1. We could automatically also source the `node_modules` of all included plugins (least safe, most convenient) 
2. We could note in a warning at boot that "plugin A require plugin B... add this to your package.json and try again" (safe, not that convenient)
3. We could note in a warning at boot that "plugin A require plugin B... you can add `node_modules/plaugin-a/node_modules` to your `api.config.general.paths.plugn`" (safe, even less convenient)
4. something else?

**Comment by l0oky** [comment]
4. Note a warning on plugin A install that "plugin A requires plugin B" and "Do you want to add this plugin B to your `package.json`? yes/no/all". In development mode If the user is confident enough he can choose whether to ignore these messages and add these plugins via a setting in `package.json` or somewhere else? 

I wouldn't worry about the security that much, since It's all open source and the user has all the responsibility what they install their machines. Unless a third party hacker targets your server filesystem, then you could deny plugin install in production mode? What's your main security concern?

**Comment by l0oky** [comment]
4. Note a warning on plugin A install that "plugin A requires plugin B" and "Do you want to add this plugin B to your `package.json`? yes/no/all". In development mode If the user is confident enough he can choose whether to ignore these messages and add these plugins via a setting in `package.json` or somewhere else? 

I wouldn't worry about the security that much, since It's all open source and the user has all the responsibility what they install their machines. Unless a third party hacker targets your server filesystem, then you could deny plugin install in production mode? What's your main security concern?

**Comment by l0oky** [comment]
Or we could make a global list of actionhero trusted plugins/modules, and If the plugin/module is not on the list, give user a warning that module/plugin is untrusted by actionhero community. That requires a bit work - but If security is our main concern so be It.

**Comment by neilstuartcraig** [comment]
Hey all. 

Seems to me that plugins are the same as any other node package for at least most purposes - i.e. as @l0oky says, they're really each persons responsibility to audit and be sure of. The node package deps of plugins will be just used/run so i don't really know why we'd treat plugins any differently - am i missing something?

So, i think from @evantahler's list above, #1 would be the most node-like and thus fits with the principle of least surprise. #2 & #3 are the most secure though and i can see them being desirable.

Making e.g. a curated list of plugins would be fraught with pain and very time-consuming, one persons opinion on "OK" will not be anothers and i suspect there'd be major issue with people wanting their new plugins to be added to the list very quickly...it's a no go in my opinion.

My opinion is that #1 should be default but #2 & #3 (which are the same from the PoV of work required - make a warning on boot and don't source plugin deps which are plugins) should be configurable as options. I don't think this is going to add any runtime overhead, just a condition on booting.

How does that sound? Just my personal take on it from having read the above (i missed most of it on gitter).

Cheers

**Comment by l0oky** [comment]
I agree with @neilstuartcraig. I added some additional ideas we can consider - just so we have more options on the table :)

**Comment by evantahler** [comment]
I'm leaning towards #1 as well.  I personally don't want to audit every (potential) plugin for security, and I don't imagine anyone would either :smile:  

The "security" I'm most worried about is not so much about "hackers" but the integrity of the system.  Say for example your project looks like this:

```
| - node_modeules
| -- ah-sequelize-plugin
| -- ah-auth-plugin
| ---- node_modules
| ------ ah-sequelize-plugin
```

Your project in general uses sequelize, as does the `ah-auth-plugin`.  How do we know which version source into the project?  If the version are more-or-less the same, the top-level project one should win, but there may be occasions where you would want both.  All of a sudden load order matters, as you have 2 `ah-sequelize-plugin\initializers\sequelize.js` to load now, each with the same name and modifying the `api` object in the same way.

NPM already handles a lot of this for you, IE: if you require `ah-sequelize-plugin v1.x.x` and the plugin requires `ah-sequelize-plugin v1.2.3`, you'll only have the one top level package installed... but if the versions drift, very strange things could happen.   To solve for this, I think our nested plugin logic probably looks something like this:

1. load all local files first (actions/initializers/etc)
2. follow all explicitly defined links (to the explicit plugins)
   - if there's a conflict, for example both your top-level project and a plugin define "my action" crash and throw an exception
3. source the linkfiles of the plugins
   - check if we've already loaded that plugin by name.  If we have, don't do it again.  There may be a version inconsistency, but that was an explicit choice by the top-level project or an incompatibility between 2 plugins... and the user has to sort that out
   - only source the node_modules of *that* plugin for any additionally needed plugins (recursive)
   - if we ever hit a plugin we've already loaded up, in this case, rather than throwing an exception, ignore it and use the one we've already got loaded + log a message.

So if your project looked like this:

```
| - node_modeules
| -- ah-sequelize-plugin
| -- ah-auth-plugin
| ---- node_modules
| ------ ah-sequelize-plugin
| -- ah-orm-plugin
| ---- node_modules
| ------ ah-sequelize-plugin
```

We would use the top-level `ah-sequelize-plugin` and throw no errors or warnings at boot

If your project looked like this (with no top-level ah-sequelize-plugin):

```
| - node_modeules
| -- ah-auth-plugin
| ---- node_modules
| ------ ah-sequelize-plugin
| -- ah-orm-plugin
| ---- node_modules
| ------ ah-sequelize-plugin
```
You would get a message like this at boot:
`ah-orm-plugin requires "ah-sequelize-plugin", but we've already loaded it from "ah-auth-plugin".  Be sure the versions are compatible.`

* misc note:
It is going to become important for plugin maintainers to be sure they link their dependancies before publishing.  For the obvious reasons, and so they can pull up any config files.  If `ah-auth-plugin` requires `ah-sequelize-plugin`, the published version of `ah-auth-plugin` better also include the `database.js` sequelize needs so that it can be then re-coppied up to the top-level project on install.

**Comment by l0oky** [comment]
I suggest we read a "pluginDependencies" key in `package.json` from plugin root. 

Example:

```json
{
  "name": "ah-sample-plugin",
  "version": "1.0.0",
  "main": "sample.js",
  "pluginDependencies": {
    "ah-sequelize-plugin": "latest"
  },
  "dependencies": {
    "jsonwebtoken": "^7.0.0",
    "bluebird": "^3.4.0",
    "node-uuid": "^1.4.7",
  },
  "devDependencies": {
    "mocha": "latest",
    "should": "latest",
    "request": "latest",
    "sinon": "latest"
  }
}

```

**Comment by evantahler** [comment]
@l0oky we don't need to add anything extra to `package.json` as noted above.  NPM handles the dependencies for us already.   If you package has a linked plugin checked into it, it should be followed... that's the proposal anyway.

The hard part is picking *which* sub-package to load in the event there are conflicts.  Now that NPM flattens all dependancies, it's a harder problem

**Comment by gcoonrod** [comment]
Should this issue still be open? @evantahler

**Comment by evantahler** [comment]
fascinatingly, we haven't had this feature for over 6 months now, and no one seems to have complained. I was *sure* that someone would need this...   

I guess we can close it!
