### ISSUE TITLE
auto namespace plugin actions

### ISSUE THREAD

**Issue by Zougi** [evantahler/actionhero#770]
The idea comes from the master himself https://github.com/S3bb1/ah-dashboard-plugin/issues/5
every action a plugin has, could be prefixed with it's name (from package.json).
It'd be great for 2 things:
- no conflict with actionhero's root project
- the list of actions at, by default, http://localhost:8080 would be sorted

I installed ah-dashboard-plugin...now when I navigate to the doc api at http://localhost:8080 there are so many actions I can bearly find the ones of my own project.

**Comment by evantahler** [comment]
While I like the organization that would produce, I don't like changing the names of actions automatically.  This would have dire effects on routing and however else folks integrate with the plugin.  That said, it's a great "best practice" that plugin authors should follow!

Send in a pull request with a note to that effect for the docs!

**Comment by S3bb1** [comment]
Yeah. Auto prefixing would be tricky because the Plugin author has to handle. 

In the project this issue is still open because it must be done sometime. 

But what maybe can be great...to group the actions on the startpage to get clearlier informations about the actions.

**Comment by evantahler** [comment]
@S3bb1 sure, that would be cool.
I usually name my actions in the style `object:method`, so things like "user:create" and "user:edit" (example here https://github.com/evantahler/actionhero-angular-bootstrap-cors-csrf/blob/master/actions/user.js).

Again, pull requests welcome! 
If this is just a UI thing for index.html, I would suggest parsing action names for both ":" and "-" to group.

**Comment by neilstuartcraig** [comment]
Same here @evantahler (though I use / as a separator). This would have wreaked havoc with my apps :-)

Maybe we should have a doc to suggest how to namespace? Or maybe even a doc of best practices/community idioms

**Comment by evantahler** [comment]
@neilstuartcraig I guess we should pick a "best practice" for the docs... however the choice of name-spacing break character (`:`, `#`, `-`, `/`, etc) seems totally arbitrary to me, and I really don't want to enforce something that is that arbitrary. 

Thoughts?

**Comment by S3bb1** [comment]
Yeah a section for best practices / templates would be great. 

I think that it is not the right way to enforce a break character ... but the right way is to **have** a break character to separate different logics

This helps developers to start easily with a clear project structure.

**Comment by neilstuartcraig** [comment]
Agreed @evantahler & @S3bb1- I think the separator is arbitrary and a personal choice. I use / because my action names then match the http request path but that's just my way. 

I was really referring in general to creating a starter set of best practices and recommendations to help new folks get up and running whilst avoiding potential issues.

**Comment by S3bb1** [comment]
Maybe we can add also some "pitfalls" if they exist.

**Comment by evantahler** [comment]
sounds like a great idea guys! 
Make a PR for some changes to the /docs site, and we'll work on this over there. 

Closing this PR in favor of that one...
