### ISSUE TITLE
Using the `ActionheroClient.prototype.actionWeb` method

### ISSUE THREAD

**Issue by running-coder** [evantahler/actionhero#772]
Hey, my case is pretty simple, at some point in my application the user is not connected with the WS so the condition falls back inside the `actionWeb` method. I was playing around trying to understand how change the request type to `GET` and found out the `httpMethod` option.

[params.httpMethod](https://github.com/evantahler/actionhero/blob/v13.0.2/client/actionheroClient.js#L194)

The `xmlhttp.send(JSON.stringify(params));` works for a `POST` request but does not work with a `GET` unless I'm missing something.

My code looks like:
``` javascript
client.action("gameHistoryViewAll", {httpMethod: 'GET', gameId: 42}, function (apiResponse) {
    console.log(apiResponse)
});
```

![2016-02-18_1341](https://cloud.githubusercontent.com/assets/7377382/13154133/7d076220-d645-11e5-9e35-82aefeb6695b.png)

![2016-02-18_1342](https://cloud.githubusercontent.com/assets/7377382/13154137/8084fbec-d645-11e5-9cc4-dbdbec89c8de.png)

As you can see it's missing the `gameId` parameter inside the query string

**Comment by evantahler** [comment]
If you change the method to `GET`, you actually need to serialize the params to URL variables, IE: `site.com?thing=stuff`.  

Send in a PR which checks for GET and modifies the URL (which is what would be needed)

**Comment by running-coder** [comment]
I've slightly modified the method to include the `GET` case. The `toUpperCase` is not mandatory but I have the habit of always doing strict comparisons

``` javascript
ActionheroClient.prototype.actionWeb = function(params, callback) {
  var xmlhttp = new XMLHttpRequest();
  xmlhttp.onreadystatechange = function () {
    var response;
    if(xmlhttp.readyState === 4) {
      if(xmlhttp.status === 200) {
        response = JSON.parse(xmlhttp.responseText);
      }else{
        try{
          response = JSON.parse(xmlhttp.responseText);
        }catch(e){
          response = { error: {statusText: xmlhttp.statusText, responseText: xmlhttp.responseText} };
        }
      }
      callback(response);
    }
  };

  var method = (params.httpMethod || 'POST').toUpperCase();
  var url = this.options.url + this.options.apiPath + '?action=' + params.action;

  if (method === 'GET') {
    for (var param in params) {
      if (~['action', 'httpMethod'].indexOf(param)) continue;
      url += '&' + param + '=' + params[param];
    }
  }

  xmlhttp.open(method, url, true);
  xmlhttp.setRequestHeader('Content-Type', 'application/json');
  xmlhttp.send(JSON.stringify(params));
}
```

**Comment by evantahler** [comment]
Looks like you are on the right track.  Please commit this as a pull request so we can track changes and discuss it with the tools github offers. 

Thanks!

**Comment by evantahler** [comment]
closed by https://github.com/evantahler/actionhero/pull/776
