### ISSUE TITLE
Issue with api.log when plugin target does not exist

### ISSUE THREAD

**Issue by S3bb1** [evantahler/actionhero#847]
When you generate a link file in the initalizers plugin folder with a name of a plugin not exists, actionHero crashes, because api.log does not exist.

`TypeError: api.log is not a function
    at F:\dev\test\node_modules\actionhero\initializers\utils.js:141:23
    at Array.forEach (native)
    at Object.api.utils.recursiveDirectoryGlob (F:\dev\test\node_modules\actionh
ero\initializers\utils.js:117:29)
    at F:\dev\test\node_modules\actionhero\initializers\utils.js:123:33
    at Array.forEach (native)
    at Object.api.utils.recursiveDirectoryGlob (F:\dev\test\node_modules\actionh
ero\initializers\utils.js:117:29)
    at F:\dev\test\node_modules\actionhero\actionhero.js:118:69
    at Array.forEach (native)
    at F:\dev\test\node_modules\actionhero\actionhero.js:117:47
    at F:\dev\test\node_modules\async\lib\async.js:718:13`

**Comment by evantahler** [comment]
The offending line: https://github.com/evantahler/actionhero/blob/master/initializers/utils.js#L141
