### ISSUE TITLE
 Authentication example link doesn't work

### ISSUE THREAD

**Issue by marcmmx** [evantahler/actionhero#861]
The authentication example link on the website doesn't work. Regards

**Comment by evantahler** [comment]
Can you be more specific?  Which link?

**Comment by marcmmx** [comment]
https://blog.evantahler.com/blog/authentication-with-actionHero-again.html <https://blog.evantahler.com/blog/authentication-with-actionHero-again.html>

**Comment by evantahler** [comment]
Ah, Thanks! https://github.com/evantahler/actionhero/commit/fccca1fb9d07d35a71b113c555d345946c476699
