### ISSUE TITLE
api.tasks.details Queue Inspection Function Broken

### ISSUE THREAD

**Issue by johnferro** [evantahler/actionhero#863]
With the latest change to the tasks initializer (bf49789) I think a bug was introduced to the api.tasks.details function.  The first job that is pushed for async processing has its callback invoked in the case of an error but not if the job completes successfully [(See here)](https://github.com/evantahler/actionhero/blob/master/initializers/tasks.js#L242). From what I've seen this causes the api.tasks.details to never complete.  I was able to get the function to finish by adding `return done();` after line 242 so that part of the function reads as follows:

```javascript
jobs.push(function(done){
  api.tasks.allWorkingOn(function(error, workers){
    if(error){ return done(error); }
    details.workers = workers;
    return done();
  });
});
```

**Comment by evantahler** [comment]
totally broken.  Fixed here https://github.com/evantahler/actionhero/pull/865
