### ISSUE TITLE
i18n localization

### ISSUE THREAD

**Issue by miguelavaqrod** [evantahler/actionhero#873]
Hi!
First of all I have to say that I discovered AH a few days ago and I am impressed. Thanks for this piece of code!

I am testing it and found an issue that maybe it is a bug, maybe it is something I am doing wrong...

I am using an initializer to create the static method (lookup) to localize client requests as explained in documentation, but even when I check that the returned value is the one I need (I use locale module to parse accept-language header, and, as it sometimes returns the system default locale, I use underscore to discard that if it is not in the "provided languages"), AH always use the default locale set.

At the end I opt to "force" api.i18n to the desired locale using the setLocale function provided.
That way, it works fine.
A bug?

Thanks in advance,

PD: I pasted below my initializer code... maybe it is useful for somebody...
Miguel

```js
'use strict';

var locale = require("locale");
var _ = require("underscore");

module.exports = {
  initialize: function(api, next){
    api.customLocalization = {
      lookup: function(connection){
        var clocale = 'en';
        if(connection.type === 'web'){
            var supported = new locale.Locales(api.config.i18n.locales);
            var locales = new locale.Locales(connection.rawConnection.req.headers["accept-language"]);
            var ulocale = locales.best(supported).toString();
            if(_.indexOf(api.config.i18n.locales, ulocale) !== -1){
                clocale = ulocale;
            }
        }
        /* IF NOT, IT DOES NOT LOCALIZE */
        api.i18n.setLocale(clocale);
        /* --- */
        return clocale;
      }
    };
    next();
  },
  start: function(api, next){
    next();
  },
  stop: function(api, next){
    next();
  }
};
```

**Comment by evantahler** [comment]
I don't think I follow what you are trying to do here.  The line `api.i18n.setLocale(clocale)` seems to set the system locale, but if you are trying to respond to a client in the proper language, you actually need to set the connection's locale. '

To set the connection's locale, you should tell the config  (https://github.com/evantahler/actionhero/blob/master/config/i18n.js#L18-L21) which method to use. This is the method which probably uses `locale` to check the accept-headers

**Comment by miguelavaqrod** [comment]
Hi Evan!

I will try to explain it better...

In config/i18n.js, I set determineConnectionLocale to 'api.customLocalization.lookup'.
Later, I creatd the initializer I mention above (with the "lookup" method).

What I am trying to do is offer the client localized messages based on the client's browser language (based on accept-language headers).

On every client request, I can see that the lookup method is executed and it returns the right locale ("es" in my case -- "clocale" variable).

This is my actions/index.js handler:

exports.index = {
    name: 'index',
    description: 'API Index',
    run: function(api, data, next){
        data.response.id = api.id;
        data.response.message = api.i18n.localize('Welcome to my API');
        data.response.uptime = new Date().getTime() - api.bootTime;
        next();
    }
};

Problem... it always localize the "Welcome to my API" in the default language ("en").
So, I set "api.i18n.setLocale(clocale)" in the initializer and it localize fine.

Having said that...
I think I am the one doing things wrong... if, as you said "The line api.i18n.setLocale(clocale) seems to set the system locale", I am setting the SYSTEM locale, I think I am changing the locale for ALL clients, and not only the client request... don't I?

I think the correct handler would be:

exports.index = {
    name: 'index',
    description: 'API Index',
    run: function(api, data, next){
        data.response.id = api.id;
        data.response.message = **data.connection.localize('Welcome to my API');**
        data.response.uptime = new Date().getTime() - api.bootTime;
        next();
    }
};

Going to test it!!

Thanks again!

**Comment by evantahler** [comment]
yay!

**Comment by evantahler** [comment]
It would be awesome if you were to write a blog post about your experiences with this.

**Comment by miguelavaqrod** [comment]
Hi!
I am a bit new using AH, but if you think my experience will help, for sure I will!
Please inform me about how and where I have to proceed.

:-)

**Comment by evantahler** [comment]
The best/simplest place to write is probably https://medium.com.... just use the `actionherojs` tag!

If you join the team on slack http://slack.actionherojs.com we can talk more there!

**Comment by miguelavaqrod** [comment]
Ok then! :-)
