### ISSUE TITLE
AH Cluster logs to default stdout for docker 

### ISSUE THREAD

**Issue by daper** [evantahler/actionhero#887]
### Log AH Cluster mode to the default stdout
Specifications
- ActionHero Version: `13.4.1`
- Node.js Version: `4.4.7`
- Operating System `CoreOS`

### Description
I know this is not a really issue, but I've tried and can't configure logger to get all workers and masters outputs to send logs to the default stdout. This is necessary for me, becouse I've deployed the application on docker engine using containers, and I've configured the log driver to send it to google cloud bucket. So for now I only have the cluster.log logs.

I've been working arround with the config file `logger.js` and removed the `if(cluster.isMaster)` statement. But wasn't works.

If anyone could help me with this. Thank you.

**Comment by evantahler** [comment]
A few notes on this:
- The logger which the binary executer uses is a little different than the normal actionhero logger, and can be found here: https://github.com/evantahler/actionhero/blob/master/bin/actionhero#L16-L40
- Why would you want to use the cluster wrapper around actionerho within Docker?  That violates the "one container-one process" rule.  I don't think you actually want the properties that the cluster manager provides:
  - you don't want more than one worker (as you should use Docker's scaling properties here, not actionhero's, IE: swarm, compose, etc).  You also don't want dynamic in-container scaling
  - you don't want the server to automatically be restarted.  You want the container to exit if the server exist; you want the errors bubbled up through the docker monitoring chain
  - you don't want want hot-reload of code (when changed).  That should be a new VM.

**Comment by daper** [comment]
Many thanks, you are right... One container - one process. I'll change my approach.
