### ISSUE TITLE
[Question] How do i handle errors?

### ISSUE THREAD

**Issue by seemsindie** [evantahler/actionhero#888]
Hello, it's not an issue, but a question.

I am using actionhero for an api for my application, but i have a huge problem handling errors.
In actions if i put stuff in inputs and set it to required i get one error message with some status code, let's say 422, but in my middleware i trow errors like:
`return next(new Error('Error Generating Token'));`

And that is producing same format but status is different(400)...

What i am asking how i can unify the errors to return codes, so i can translate the text for error on client side, can you suggest how to do it?

**Comment by l0oky** [comment]
When you `return next()` in middleware actionhero will process the action that was requested. The first parameter in `next()` is an object (not `Error()` object) - this object will then be stringified into an `error:{}` object and returned as a response to client. So what you want to do is something like this 

```javascript
return next({message: 'Error Generating Token'});
```

So the response would look something like:

```json
{
 "error":{
   "message":"Error Generating Token"
 }
}
```

**Comment by evantahler** [comment]
Thanks @l0oky!
