### ISSUE TITLE
status action should be better

### ISSUE THREAD

**Issue by evantahler** [evantahler/actionhero#893]
- include avg event loop delay for past (now, 5 min, 10 min)
- include avg memory usage for same window
- include avg resque queue length

cc @gcoonrod

**Comment by evantahler** [comment]
sample time and reporting time should be configuable

**Comment by gcoonrod** [comment]
Should these functions be in the action or should they be added as an initializer and then exampled in the status action?

**Comment by evantahler** [comment]
The methods which do the sampling (taking the queue length, memory usage, and event loop delay) will need to be run via an initializer, and probably populate something like `api.statusSamples`

**Comment by evantahler** [comment]
solved by https://github.com/evantahler/actionhero/pull/895
