### ISSUE TITLE
generateAction config redis.js

### ISSUE THREAD

**Issue by tienne** [evantahler/actionhero#903]
hi
I am the developer of Korea
Not English a little

my os is window10 and i use cross-env, so my actionhero start scripts 
'''
cross-env PORT=8081 FAKEREDIS=false actionhero start
'''
but Since actionHero version 14.0.1 releases for redis config 
actionhero generate error to config redis.js
i not use fakeredis
hero my case

- ActionHero Version: `14.0.10`
- Node.js Version: `4.4.5`
- Operating System `Windows 10)`

# Steps to reproduce your error
- actionhero generateAction --name=actionName
=======================================================
```
npm\node_modules\actionhero\bin\actionhero:222
      throw e;
      ^

Error: Unable to load configurations, errors: {"C:\\dev\\gmp.backend\\config\\redis.js":{"msg":"Error: Cannot find module 'f
akeredis'"}}
    at api.loadConfigDirectory (C:\dev\gmp.backend\node_modules\actionhero\initializers\config.js:138:19)
    at Array.map (native)
    at Object.module.exports.initialize (C:\dev\gmp.backend\node_modules\actionhero\initializers\config.js:169:17)
    at C:\Users\tienne\AppData\Roaming\npm\node_modules\actionhero\bin\actionhero:211:18
    at Object.module.exports.initialize (C:\dev\gmp.backend\node_modules\actionhero\initializers\utils.js:278:5)
    at Object.<anonymous> (C:\Users\tienne\AppData\Roaming\npm\node_modules\actionhero\bin\actionhero:209:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```
---

**Comment by tienne** [comment]
hero my config/redis.js

exports['default'] = {
  redis: function(api){

    // konstructor: The redis client constructor method
    // args: The arguments to pass to the constructor
    // buildNew: is it `new konstructor()` or just `konstructor()`?

    if(process.env.FAKEREDIS === 'false' || process.env.REDIS_HOST !== undefined){
      return {
        '_toExpand': false,
        client: {
          konstructor: require('ioredis'),
          args: [{ port: port, host: host, password: password, db: db }],
          buildNew: true
        },
        subscriber: {
          konstructor: require('ioredis'),
          args: [{ port: port, host: host, password: password, db: db }],
          buildNew: true
        },
        tasks: {
          konstructor: require('ioredis'),
          args: [{ port: port, host: host, password: password, db: db }],
          buildNew: true
        }
      };
    }else {
      return {
        '_toExpand': false,
        client: {
          konstructor: require('fakeredis').createClient,
          args: [port, host, {fast: true}],
          buildNew: false
        },
        subscriber: {
          konstructor: require('fakeredis').createClient,
          args: [port, host, {fast: true}],
          buildNew: false
        },
        tasks: {
          konstructor: require('fakeredis').createClient,
          args: [port, host, {fast: true}],
          buildNew: false
        }
      };
    }
  }
};

**Comment by evantahler** [comment]
Don't worry! Your report here is easy to understand.
---
Do you have `fakeredis` installed and part of your project's `package.json`?

**Comment by l0oky** [comment]
When you `actionhero generate`, you'll need to also `npm install`. After that your good to go, `actionhero generateAction --name=actionName`.

**Comment by tienne** [comment]
@evantahler myproject package.json not include fakeredis

**Comment by evantahler** [comment]
For newly generated projects it will https://github.com/evantahler/actionhero/blob/master/bin/templates/package.json
