### ISSUE TITLE
Using generic Action into Action

### ISSUE THREAD

**Issue by thEpisode** [evantahler/actionhero#911]
Hi, I have a generic Action, e.g: "SendSMS" and I want to use it into another Action like "Login".

I want to know how to make this.

- ActionHero Version: `13.4.0`
- Node.js Version: `4.4.7`
- Operating System `Windows 10, Ubuntu Server 14.04 LTS`

**Comment by chimmelb** [comment]
The general idea would be to put your core logic into `initializers`, and call those initializers from the `actions`.  This way your core logic can be used from `actions` or `tasks`, and mixed any way you need it to be.

So your sms initializer might be at `api.sms` and your login initializer might be `api.auth`, and in an action you would chain the two like:

```
api.sms.send( arg1, arg2, function(err, data){
  if( err ){
    //finish the action
    return next(err);
  }
  api.auth.login( data.whatever, function( err, reply ){
      if( err ){
      //finish the action
      return next(err);
    }
    //finish action callback
    api.response.success = reply;
    next();  
  }
}

**Comment by thEpisode** [comment]
Uhmm!, it's ok!, thank you so much! :dancer:
