### ISSUE TITLE
when using real redis the tasks can not run

### ISSUE THREAD

**Issue by yinwz** [evantahler/actionhero#933]
OS: WIN10
Node.js：4.4.5
actionhero： 15.0.2
ioredis：2.3.0
redis：2.6.12 32bit

**Comment by l0oky** [comment]
What does your redis config look like? Can you post it here? Did you just upgrade your actionhero project?

**Comment by yinwz** [comment]
redis 127.0.0.1:6379> config get *
 1) "dbfilename"
 2) "dump.rdb"
 3) "requirepass"
 4) ""
 5) "masterauth"
 6) ""
 7) "bind"
 8) ""
 9) "unixsocket"
10) ""
11) "logfile"
12) ""
13) "pidfile"
14) "/var/run/redis.pid"
15) "maxmemory"
16) "3221225472"
17) "maxmemory-samples"
18) "3"
19) "timeout"
20) "0"
21) "tcp-keepalive"
22) "0"
23) "auto-aof-rewrite-percentage"
24) "100"
25) "auto-aof-rewrite-min-size"
26) "1048576"
27) "hash-max-ziplist-entries"
28) "512"
29) "hash-max-ziplist-value"
30) "64"
31) "list-max-ziplist-entries"
32) "512"
33) "list-max-ziplist-value"
34) "64"
35) "set-max-intset-entries"
36) "512"
37) "zset-max-ziplist-entries"
38) "128"
39) "zset-max-ziplist-value"
40) "64"
41) "lua-time-limit"
42) "5000"
43) "slowlog-log-slower-than"
44) "10000"
45) "slowlog-max-len"
46) "128"
47) "port"
48) "6379"
49) "databases"
50) "16"
51) "repl-ping-slave-period"
52) "10"
53) "repl-timeout"
54) "60"
55) "maxclients"
56) "10000"
57) "watchdog-period"
58) "0"
59) "slave-priority"
60) "100"
61) "hz"
62) "10"
63) "no-appendfsync-on-rewrite"
64) "no"
65) "slave-serve-stale-data"
66) "yes"
67) "slave-read-only"
68) "yes"
69) "stop-writes-on-bgsave-error"
70) "yes"
71) "daemonize"
72) "no"
73) "rdbcompression"
74) "yes"
75) "rdbchecksum"
76) "yes"
77) "activerehashing"
78) "yes"
79) "repl-disable-tcp-nodelay"
80) "no"
81) "appendonly"
82) "no"
83) "dir"
84) "D:\\yinwz\\Desktop\\iotmw"
85) "maxmemory-policy"
86) "noeviction"
87) "appendfsync"
88) "everysec"
89) "save"
90) "3600 0 300 0 60 0"
91) "loglevel"
92) "notice"
93) "client-output-buffer-limit"
94) "normal 0 0 0 slave 268435456 67108864 60 pubsub 33554432 8388608 60"
95) "unixsocketperm"
96) "0"
97) "slaveof"
98) ""

**Comment by yinwz** [comment]
redis 127.0.0.1:6379> keys  *
1) "resque:workers"
2) "resque:worker:yinwz-pc:6244+1:default:started"
3) "resque:queue:default"
4) "resque:resque_scheduler_master_lock"
5) "resque:connection_test_key"
6) "resque:stat:processed"
7) "resque:stat:processed:yinwz-pc:6244+1"
8) "actionhero:cache:__session:e778a269def57578491ce76fa0bcbb2c6a44b085"
9) "resque:queues"

**Comment by evantahler** [comment]
You are sharing the contents of your redis database, not your configuration file in `config/redis.js`.  

It does look like actionhero/resque are creating  data, so that's a good sign!

**Comment by yinwz** [comment]
`process.env.FAKEREDIS = false;
var host     = process.env.REDIS_HOST || '127.0.0.1';
var port     = process.env.REDIS_PORT || 6379;
var db       = process.env.REDIS_DB   || 0;
var password = process.env.REDIS_PASS || null;

exports['default'] = {
  redis: function(api){

    // konstructor: The redis client constructor method
    // args: The arguments to pass to the constructor
    // buildNew: is it `new konstructor()` or just `konstructor()`?

    if(process.env.FAKEREDIS === 'false' || process.env.REDIS_HOST !== undefined){

      return {
        '_toExpand': false,
        client: {
          konstructor: require('ioredis'),
          args: [{ port: port, host: host, password: password, db: db }],
          buildNew: true
        },
        subscriber: {
          konstructor: require('ioredis'),
          args: [{ port: port, host: host, password: password, db: db }],
          buildNew: true
        },
        tasks: {
          konstructor: require('ioredis'),
          args: [{ port: port, host: host, password: password, db: db }],
          buildNew: true
        }
      };

    }else{

      return {
        '_toExpand': false,
        client: {
          konstructor: require('fakeredis').createClient,
          args: [port, host, {fast: true}],
          buildNew: false
        },
        subscriber: {
          konstructor: require('fakeredis').createClient,
          args: [port, host, {fast: true}],
          buildNew: false
        },
        tasks: {
          konstructor: require('fakeredis').createClient,
          args: [port, host, {fast: true}],
          buildNew: false
        }
      };

    }
  }
};
`

**Comment by yinwz** [comment]
btw：the same code is running ok on linux

**Comment by l0oky** [comment]
Oh of course, ActionHero has many hidden issues/bugs on windows...
Could you recreate the issue in a project so we can dig more into it?

**Comment by yinwz** [comment]
I has given up the attempt on windows.

**Comment by evantahler** [comment]
This is a shame.  I know a number of people happily use actionhero and redis on windows.  If you can provide more detail, perhaps we can help?

**Comment by evantahler** [comment]
How did you install redis on windows?

**Comment by yinwz** [comment]
NOW, It is running OK.
I reinstall the  newest version of redis on windows.
https://github.com/MSOpenTech/redis/releases

**Comment by evantahler** [comment]
ok... so we'll chalk it up to the totally unsupported port of Redis on windows :D
