### ISSUE TITLE
Cannot use PM2 with --no-daemon flag

### ISSUE THREAD

**Issue by Martinlck** [evantahler/actionhero#944]
Cannot use PM2 for clustering AH.

Hello @evantahler, first of all, let me tell you I'm very happy with AH and I love how solid it is.
Now to the question, issue, or bug, dont know, maybe this is not supported anymore, but on version 14 of AH I could easily start AH with pm2 on cluster mode. After I updated to AH 15 (Because I needed the latest version of node-resque), I couldnt find a way to do it, I always get an error by running:
pm2 start -i 0 --no-daemon /opt/app/node_modules/.bin/actionhero

Which was working before on AH 14. So I tried to use the AH built in cluster mode, but the problem is that raven does not catch fatal errors and it crashes the server without gracefully shutting it down, which I need to happen so it clears user data in case of restart. I'm using socket server only since I have a realtime PVP game working on it.
Is this an issue? You dont support PM2 anymore? If that's the case, is there anyway that on uncaughtException I can gracefully shutdown the server? And if none of the above apply, is there anyway that I can update node-resque without upgrading AH to 15?.
Thanks again for your help and for building this amazing project.

- ActionHero Version: `15`
- Node.js Version: `latest stable`
- Operating System `Ubuntu 14`

**Comment by evantahler** [comment]
I'm glad that actionhero is working out for you!

We didn't change anything to stop working with PM2 explicitly (nor did we ever explicitly support it).  Can you share more detail about the errors you are getting?
In the current version of ActionHero, this seems to work:

`pm2 start "./node_modules/.bin/actionhero" --name 'actionhero' -- start` 

for one node, and then

`pm2 start ./node_modules/.bin/actionhero -i 0 --name 'actionhero' -- start`

for the cluster.  (tested on OSX).

**Comment by Martinlck** [comment]
Thanks a lot @evantahler, and yes you are right it works with no problem with that command. Yet the flag --no-daemon that I use on PM2 it throws me an error, so is this command:
pm2 start --no-daemon -i 0 ./node_modules/.bin/actionhero --name 'actionhero' -- start

Throws this: 
{"level":"notice","message":"*** Starting ActionHero ***","timestamp":"172.17.0.2:331 @ 2016-09-19T06:02:37.859Z"}
{"level":"error","message":"Error: `start /opt/app/node_modules/.bin/actionhero start start` is not a method I can perform.","timestamp":"172.17.0.2:331 @ 2016-09-19T06:02:38.053Z"}
{"level":"error","message":"run `actionhero help` to learn more.","timestamp":"172.17.0.2:331 @ 2016-09-19T06:02:38.053Z"}

I need the no daemon flag since I'm starting it on a docker container and without it the container exits. I guess the name of the problem is wrong, since is not that I cannot start it in cluster mode.
I'll update it.
Again thanks for your help and for building this amazing project!
