### ISSUE TITLE
[Enhancement Request] Modify Failed Task Behaviour

### ISSUE THREAD

**Issue by gcoonrod** [evantahler/actionhero#954]
# Prevent Failed Tasks From Being Written to Redis
Currently when a task fails, Resque persists it into the `resque:failed` set in Redis. Overtime, if these failed tasks aren't cleared out, it can lead to Redis running out of cache space. For a deployment of ActionHero that is particularly dependent on task processing this can lead to serious failures.

While the majority of the work needed to add this enhancement will be in the [node-resque](https://github.com/taskrabbit/node-resque/issues/170) project. A means to configure this behavior will be needed in ActionHero. 

I propose that a section be added to `config/tasks.js` file:
```javascript
{
    failureHandling: {
        persist: true, //default is true
        ttl: -1, // if persist === true && ttl > 0 set ttl on failed value,
    }
}
```

- ActionHero Version: `12.5.0`
- Node.js Version: `4.2.3`
- Operating System `(OSX, AWS ElasticBeanstalk)`

# Steps to reproduce your error
- Create a task that always calls `next(new Error());`
- Set it to run every 100 milliseconds
- Wait for Redis to fill up :)

---

If your "issue" does not fit into this template, it might not be an issue!  Please join our [slack team](http://slack.actionherojs.com) and ask the question of the community there.

**Comment by evantahler** [comment]
related to `node-resque` https://github.com/taskrabbit/node-resque/issues/170

**Comment by evantahler** [comment]
Closing (but keeping the node-resque issue open)
