### ISSUE TITLE
Worker become unresponsive

### ISSUE THREAD

**Issue by itopenup** [evantahler/actionhero#955]
When starting actionhero in cluster mode with `start cluster` worker does not responses after about 40 requests.

- ActionHero Version: `15.1.0`
- Node.js Version: `6.4.0`
- Operating System `Ubuntu 14.04`

# Steps to reproduce
start with `start cluster --daemon --workers=1`
make one request many times with 1 sec delay
---

After 42-43th request the worker become not responsive. Unable to reload with `kill -s HUP 'cat pids/cluster_pidfile'`. Killing the cluster process helps only.

Try to start with 2 workers. Hangs after 85 requests )

Starting without `cluster` works well, have answers for all requests.

**Comment by evantahler** [comment]
We'll certainly need some details to be able to reproduce this.  Lots of folks use cluster mode in production (on Ubuntu) without issue.  Can you share a specific action or initializer which causes the problem?  are you making HTTP requests outside of your app sourced from an action?

**Comment by itopenup** [comment]
I have this action:

`'use strict';

exports.getECG = {
    name: 'getECGs',
    summary: 'Get ECG\'s of account by id',
    description: 'Get ECG\'s of account by id',

    tags: ['ECG'],

    authenticated: true,

    headers: {
        Authentication: {
            required: true
        }
    },

    inputs: {
        id: { required: true },
    },

    run: function (api, data, next) {

        api.mongo.Account.findById(data.params.id)
            .populate({ path: 'analyzes', match: { deleted: false } })
            .exec((err, user) => {
            
            if (err) {
                return next(err);
            }

            if (!user) {
                data.connection.rawConnection.responseHttpCode = 404;
                return next(new Error('User not found'));
            }

            if (user.whoami !== 'patient') {
                return next(new Error('Just for patients.'));
            }

            data.response = user.analyzes;
            next();
        
        });

    }
};`

I'm making requests via curl using bash script which makes requests in a loop with i sec delay between.

**Comment by itopenup** [comment]
And for authentication I have the only action pre-processor middleware:

`'use strict';

require('sugar');

module.exports = {
    loadPriority: 1000,
    startPriority: 1000,
    stopPriority: 1000,

    initialize: function (api, next) {
        let authenticationMiddleware = {
            name: 'Authentication middleware',
            global: true,
            priority: 1,
            preProcessor: function(data, next) {

                /*
                 * params
                 * connection,
                 * action,
                 * actionTemplate
                 * ...
                 * */

                if(data.actionTemplate.authenticated === true) {

                    /*data.actionTemplate.inputs.id = {
                        required: true
                    };
                    data.actionTemplate.inputs.requesterIsPrivileged = {
                        required: true
                    };*/

                    let req = data.connection.rawConnection.req;

                    if(req.headers && req.headers['authentication']) {

                        api.cache.load(api.config.app.cacheKeys.accessToken + '_' + req.headers['authentication'],
                            function(err, value, expireAt) {

                                if(!value) {
                                    data.connection.rawConnection.responseHttpCode = 401;
                                    return next(new Error('Access token is invalid'));
                                }
                                
                                if(err) {
                                    data.connection.rawConnection.responseHttpCode = 500;
                                    return next(err);
                                }

                                api.mongo.Account.findById(value.id)
                                    .then(account => {
                                        if (account.is_blocked) {
                                            data.connection.rawConnection.responseHttpCode = 403;
                                            throw new Error('Account is blocked');
                                        }
                                        return next();
                                    })
                                    .catch(err => {
                                        return next(err);
                                    });
                            });
                    } else {
                        data.connection.rawConnection.responseHttpCode = 403;
                        return next(new Error('Authentication is required'));
                    }
                } else {
                    next();
                }
            }
        };

        api.actions.addMiddleware(authenticationMiddleware);
        next();
    },

    start: function (api, next) {
        next();
    },

    stop: function (api, next) {
        next();
    }
};`

**Comment by itopenup** [comment]
Actually it's not important how to make requests. I tried swagger, the same result.

**Comment by evantahler** [comment]
So there's a lot that can be going wrong here.  The main way to debug something like this is a lot of logging, both before an after a callback.

Is mongo getting starved of connections?  Try this:

```js
console.log('starting mongo for request: ' + data.connection.id);
api.mongo.Account.findById(data.params.id)
...
```

What about the `api.cache`?  Have you starved redis?

```js
console.log('starting cache read');
                    api.cache.load(api.config.app.cacheKeys.accessToken + '_' + req.headers['authentication'], function(error, data){
console.log('ended cache read');
```

stuff like that.

I'm sad to report that using promises make this kind of debugging almost impossible, as you can simply starve the request.  This is why all of ActionHero's methods do not ever return prommises.  To that end, you can at least log the "start" of an action and then the end... so you can tell which actions are the source of the problem.  also, if you log the start of an action, this will help you to see that it's not ActionHero that is the source of the problem :)

---

As an anecdotal note,  I've seen a number of people with problems like this, and in about 75% of them, a database driver was the problem.  They often hang unresponsively, which looks exactly like the problem you are seeing :(

**Comment by itopenup** [comment]
Thanks a lot. The reason why I opened this issue is that I saw similar issue in ActionHero. I even could not think I have a problem with mongo driver. But when I just removed Mongo-request from the action it became working.
Closing issue. Sorry for troubling )
