### ISSUE TITLE
lastModified.setMilliseconds error occurring nightly

### ISSUE THREAD

**Issue by BigForNothing** [evantahler/actionhero#962]
# lastModified.setMilliseconds error occurring nightly
Every night for awhile ( I think it may have started after version 15 ), I've started getting an error in the logs. It happens regardless if it's in a cluster or not. I've added some console.log outputs to node_modules/actionhero/servers/web.js (after line 130, inside the if statement to help. The if statement now looks like this: 

    if(reqHeaders['if-modified-since']){
      console.log('reqHeaders', reqHeaders);
      console.log(reqHeaders['if-modified-since']);
      ifModifiedSince = new Date(reqHeaders['if-modified-since']);
      lastModified.setMilliseconds(0);
      if(lastModified <= ifModifiedSince){connection.rawConnection.responseHttpCode = 304; }
      return sendRequestResult();
    }

The error: TypeError: Cannot read property 'setMilliseconds' of undefined
- ActionHero Version: `15.1.0`
- Node.js Version: `6.3.1`
- Operating System `Ubuntu 14.04 Trusty`

# Steps to reproduce your error
- Start actionhero. Normal or cluster mode doesn't matter.
- No other activity is happening until sometime in the evening.

Stack trace, including added console.log output:

```
reqHeaders { host: 'www.baidu.com',
  'user-agent': 'Mozilla',
  'if-modified-since': 'Thu, 19 Apr 2012 09:51:20 GMT' }
Thu, 19 Apr 2012 09:51:20 GMT
/home/ubuntu/xxxxx/node_modules/actionhero/servers/web.js:134
      lastModified.setMilliseconds(0);
                  ^

TypeError: Cannot read property 'setMilliseconds' of undefined
    at server.sendFile (/home/ubuntu/xxxxx/node_modules/actionhero/servers/web.js:134:19)
    at api.staticFile.get (/home/ubuntu/xxxxx/node_modules/actionhero/initializers/genericServer.js:99:14)
    at Object.api.staticFile.sendFileNotFound (/home/ubuntu/xxxxx/node_modules/actionhero/initializers/staticFile.js:80:9)
    at Object.api.staticFile.get (/home/ubuntu/xxxxx/node_modules/actionhero/initializers/staticFile.js:29:16)
    at checkExistence (/home/ubuntu/xxxxx/node_modules/actionhero/initializers/staticFile.js:45:32)
    at fs.stat (/home/ubuntu/xxxxx/node_modules/actionhero/initializers/staticFile.js:86:13)
    at FSReqWrap.oncomplete (fs.js:123:15)
```
---

**Comment by evantahler** [comment]
Very strange!
The best place to log to figure this out is actually in [`node_modules/actionhero/initializers/staticFile.js` on line 62](https://github.com/evantahler/actionhero/blob/master/initializers/staticFile.js#L62).  You can see that `lastModified` should be the results of calling `fs.stat` on your file.  To that end, log out the whole `stats` object and take a look at it. 

Are you perhaps doing any sort of file/folder rotation at the end of the day?  This could be a symptom of a changing symlink or something similar.  when you say "every night", is this UTC night, local night, etc?  Does the problem only persist for a short while and recover, or does it remain until a reboot of the application?

Also, does Baidu use actionhero?!  I'd love to talk more if it does!

**Comment by BigForNothing** [comment]
I didn't see your reply until this morning, so while it did crash overnight, I'll have to wait until tomorrow morning to get the stats object output. 

I'm not doing any rotation at all. This is currently just being used as a dev server. I have a production cluster running as well (it's in production mode, but is just an internal beta server). The incident is happening there as well. I went ahead and did a grep against the log directory for "FSReqWrap.oncomplete" and these are the timestamps: 
```
cluster.log:{"level":"alert","message":"[worker #4 (4627)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-06T07:00:49.468Z"}
cluster.log:{"level":"alert","message":"[worker #2 (4590)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-06T15:15:12.222Z"}
cluster.log:{"level":"alert","message":"[worker #1 (30954)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-11T01:13:47.757Z"}
cluster.log:{"level":"alert","message":"[worker #3 (30991)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-11T16:17:56.181Z"}
cluster.log:{"level":"alert","message":"[worker #3 (7382)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-12T05:42:43.086Z"}
cluster.log:{"level":"alert","message":"[worker #3 (5050)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-13T08:34:50.295Z"}
cluster.log:{"level":"alert","message":"[worker #4 (31011)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-13T10:13:10.760Z"}
cluster.log:{"level":"alert","message":"[worker #1 (26562)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-14T14:43:26.877Z"}
cluster.log:{"level":"alert","message":"[worker #2 (30977)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-15T19:14:23.351Z"}
cluster.log:{"level":"alert","message":"[worker #3 (32206)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-16T00:35:03.143Z"}
cluster.log:{"level":"alert","message":"[worker #5 (31030)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-16T23:41:36.811Z"}
cluster.log:{"level":"alert","message":"[worker #1 (9671)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-17T16:47:20.584Z"}
cluster.log:{"level":"alert","message":"[worker #4 (9665)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-18T04:05:41.349Z"}
cluster.log:{"level":"alert","message":"[worker #5 (9677)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-19T08:33:54.346Z"}
cluster.log:{"level":"alert","message":"[worker #1 (9918)]:        at FSReqWrap.oncomplete (fs.js:123:15)","timestamp":"2016-10-19T09:01:29.512Z"}
```

If running in cluster mode, the individual workers restart as expected and all functionality remains. When running in single mode, it drops to the command line as would be expected. 

I should also add that there are no plugins being used and I don't have any tasks being ran.

I'm sorry, I have no idea about Baidu. Since this hasn't been released publicly, I'm assuming they are just scanning IPs to see what exists.

**Comment by evantahler** [comment]
Thanks for the update.  Please let us know what the stats object looks like tonight!

**Comment by BigForNothing** [comment]
Please see the pull request, I may have resolved it for you with a quick reorder.

**Comment by evantahler** [comment]
That's something that used to only be available in the debug log level.  This will help https://github.com/evantahler/actionhero/pull/965

**Comment by evantahler** [comment]
Also, normally folks deploy actionhero behind a proxy (nginx) which does the file serving directly, and they look at the logs there

**Comment by BigForNothing** [comment]
Completely valid. I do actually have a deploy behind nginx. But since this was happening on my deployments regardless of proxy use, I didn't think to check nginx's log. Just looked at the merge. Glad to see it. Thanks!
