### ISSUE TITLE
specHelper should allow response metadata to be turned off

### ISSUE THREAD

**Issue by NamespaceValentine** [evantahler/actionhero#978]
When using specHelper, test server rules for response metadata are not respected

- ActionHero Version: `15.1.0`
- Node.js Version: `4.5.0`
- Operating System `OSX`

# Issue description
When running a unit tests with specHelper, it would be helpful if we could turn off response metadata, because it can interfere with testing the expected responses. An example of how this affects testing is as follows:

I have an action that returns a json array as a response, if I cannot turn off my metadata, the array I get back looks like:
`[ { id: 'f05f9d0a-6587-4672-8467-d02f7e525e63',
    name: 'My Box',
    path: 'app/my-box',
    category_id: 'f7ff85a0-faaa-11e5-a8a9-7fa3b294cd46' },
  { id: '498efd35-f17a-47e6-a365-f5a3a075911e',
    name: 'My Box Other',
    path: 'app/my-box-other',
    category_id: 'f7ff85a0-faaa-11e5-a8a9-7fa3b294cd46' },
  messageCount: 1,
  serverInformation: { serverName: 'cerberus-mock-api', apiVersion: '0.0.1' },
  requesterInformation: { id: 'b263bbc5-9d4b-4cd8-8c96-e125d448baf3',
    remoteIP: 'testServer',
    receivedParams: { action: 'getSafeDepositBoxList', apiVersion: 1 } } ]`

This means that in order to get the actual response, I have to do something like:
`var trueResponse = [response[0], response[1]];`

Which is not ideal. And it gets even worse for when I want to test for an empty array as a response.

In all cases where I run an actual server, these are properties I can turn off, but digging into the specHelper code, there is no way to turn this off for this mock server functionality. Ideally it should either have its own config setting that it decides on, or it should respect the test settings, or it should be able to take an options argument.

**Comment by NamespaceValentine** [comment]
My current workaround on every response is:
`delete response.messageCount;
 delete response.serverInformation;
 delete response.requesterInformation;`

**Comment by evantahler** [comment]
You can turn off `response.serverInformation` and `response.requesterInformation` as options to the web server in your `NODE_ENV=test` environment.  https://github.com/evantahler/actionhero/blob/master/config/servers/web.js#L105-L119  New projects should generate with these options.

As far as response coming as an array, that is strange! Can you share how you are using the specHelper?  You can see the specHelper in use here calling actions directly and data not coming back as an array: https://github.com/evantahler/actionhero/blob/master/test/actions/randomNumber.js

**Comment by NamespaceValentine** [comment]
If the response that I give back from my action is an array, the specHelper simply pushes it into the array. I shudder to think what it would do with a string. Here is the relevant source code from specHelper that shows that it is always appending this data, regardless of settings:
`server.on('actionComplete', function(data){
          data.response.messageCount = data.messageCount;
          data.response.serverInformation = {
            serverName:      api.config.general.serverName,
            apiVersion:      api.config.general.apiVersion,
          };
          data.response.requesterInformation = {
            id: data.connection.id,
            remoteIP: data.connection.remoteIP,
            receivedParams: {}
          };

          if(data.response.error){
            data.response.error = api.config.errors.serializers.servers.specHelper(data.response.error);
          }

          for(let k in data.params){
            data.response.requesterInformation.receivedParams[k] = data.params[k];
          }

          if(data.toRender === true){
            server.sendMessage(data.connection, data.response, data.messageCount);
          }
        });
`

My request would be that there is some env flag, option flag, or server flag that I could set that would gate the logic on whether or not this meta information is applied to specHelper responses. I get that the info can be useful, but it is information that can be disabled in servers, and so for testing it should be able to be disabled as well. Adding that information without the ability to disable it destroys the dev/prod parity and makes unit tests behave differently than actual servers. Because of this, unit tests using specHelper need to use workarounds to test that the data comes in formatted as expected in production.

**Comment by evantahler** [comment]
So the first thing that this issue points out is that we are aren't being "type safe" (as safe as you can be in JS) with regard to our error handling and metadata in the SpecHelper.  

We shouldn't do things like `data.response.error = error` if `typeof data.response === 'string'`!

This should help that https://github.com/evantahler/actionhero/pull/979

**Comment by evantahler** [comment]
And now, the actual solve to the question you initially asked: https://github.com/evantahler/actionhero/pull/980

`api.specHelper.returnMetadata = false`

**Comment by evantahler** [comment]
Closed via #979 and #980

**Comment by evantahler** [comment]
Thanks for all of your detailed descriptions!

**Comment by NamespaceValentine** [comment]
Thank you so much for the quick response and turnaround ^_^
