### ISSUE TITLE
Tasks not running (fakeredis) ?

### ISSUE THREAD

**Issue by Stuey2** [evantahler/actionhero#990]
Tasks not running (fakeredis) ?
I followed steps as per below and don't see any task output. Not sure if I'm doing something wrong, if I need to enable tasks somehow apart from via the scheduler flag. From what I can see in the documentation they should be loaded automagically if the task name matches the file name.  

I'm not sure if this is because I'm using fakeredis. There are no errors getting logged.

- ActionHero Version: `16.0.0`
- Node.js Version: `4.4.5`
- Operating System `Windows 10`

# Steps to reproduce your error
1. Get latest actionhero via npm - actionhero 16.0.0
2. Generated a project: ./node_modules/.bin/actionhero generate & run npm install
3. Generate a task: ./node_modules/.bin/actionhero generate task --name=stats --queue=default
4. Edit the frequency to 3000 and put in an api.log("Hello") into the run
5. Edit tasks.js to turn on scheduler: scheduler: true,
6. Run ... and no task output is seen

Following output is seen:
192.168.110.1 @ 2016-12-07T14:28:21.972Z - notice: *** Starting ActionHero ***
192.168.110.1 @ 2016-12-07T14:28:22.163Z - info: --------------------------------------
192.168.110.1 @ 2016-12-07T14:28:22.164Z - info: ACTIONHERO COMMAND >> start
192.168.110.1 @ 2016-12-07T14:28:22.164Z - info: --------------------------------------
192.168.110.1 @ 2016-12-07T14:28:22.167Z - notice: pid: 13824
192.168.110.1 @ 2016-12-07T14:28:22.167Z - notice: server ID: 192.168.110.1
192.168.110.1 @ 2016-12-07T14:28:22.170Z - info: actionhero member 192.168.110.1 has joined the cluster
192.168.110.1 @ 2016-12-07T14:28:22.180Z - info: resque scheduler started
192.168.110.1 @ 2016-12-07T14:28:22.181Z - notice: Starting server: `web` @ 0.0.0.0:8080
192.168.110.1 @ 2016-12-07T14:28:22.191Z - notice: Starting server: `websocket`
192.168.110.1 @ 2016-12-07T14:28:23.730Z - notice: environment: development
192.168.110.1 @ 2016-12-07T14:28:23.730Z - alert: *** ActionHero Started ***
192.168.110.1 @ 2016-12-07T14:28:27.187Z - info: This node is now the Resque scheduler master

**Comment by evantahler** [comment]
Did you turn on an taskProcessors?

https://github.com/evantahler/actionhero/blob/master/config/tasks.js#L35

**Comment by Stuey2** [comment]
Thanks Evan, that worked, thought I'd read the documentation. Just a note, some of the example tasks from: http://www.actionherojs.com/docs/overview/#examples-tasks show next(true) or next(true, null) called which throws an error, I presume the API for tasks is next() for success. Some learning to do on my part. Thanks again, I'll try the slack group if I get stuck.

**Comment by evantahler** [comment]
Ah! Thanks... some of those examples are very old. I'll update them
