### ISSUE TITLE
ActionHero Generate and Yarn don't play nicely

### ISSUE THREAD

**Issue by anhldbk** [evantahler/actionhero#991]
# Description of Issue

- ActionHero Version: `^16.0.0`
- Node.js Version: `v7.2.0`
- Operating System `Ubuntu 16`

# Steps to reproduce your error
- Make a new actionhero project with `./node_modules/.bin/actionhero generate`
- `npm start`

And I've got: 

```
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by evantahler** [comment]
You'll need to provide an error message or more details somehow.  That looks like the `generate` script failed?  Did it create the files needed?

**Comment by anhldbk** [comment]
@evantahler Thanks for your timely response. It's my fault. 

Currently I'm using `yarn` instead of `npm`. Just run `yarn add actionhero` and it will generate file `package.json` also. In this case, our actionhero generator does not replace the file with the template one.

Don't you think the generator should remove `package.json` first before generating other files?

**Comment by evantahler** [comment]
I don't think anyone has considered generating a "yarn" bootstrap project for actionhero... Care to take a crack at it?

**Comment by anhldbk** [comment]
@evantahler What's about the question of: 

> Don't you think the generator should remove package.json first before generating other files?

**Comment by evantahler** [comment]
That seems really dangerous.  The generator never removes any existing files... you might have some data in that file you want to keep around?

**Comment by anhldbk** [comment]
Wow, I think we should improve our generator a little bit. 

Here is our `package.json` if properly generated:

```js
///
 "author"      : "YOU <YOU@example.com>",
  "name"        : "my_actionhero_project",
  "description" : "my actionhero project",
///
```

**Comment by anhldbk** [comment]
@evantahler You're right! 

I think there are 2 solutions for this problem.

**Solution 1**
So the generator should detect file `package.json` (if any) and `properly` merge it with the template one, right?

But what is `properly`? Should we override or keep existing fields? 

**Solution 2**

The generator should create a new directory, just like the way `react-native` does:

```
react-native init AwesomeProject
cd AwesomeProject
react-native run-android
```

I think solution #2 is much better.

Btw, we should guide users to install `actionhero` globally, right?

**Comment by evantahler** [comment]
I personally don't like 1 or 2.  `actionhero generate` is a new project generator.  If you already have a `package.json`, you aren't running the generator to create a new project!  To that end, the generator does what it can, and won't touch any of your existing files.  

If you have ActionHero installed globally, #2 sort of already works... you just need to be *inside* your new project director.

You should never install any node package globally ever under any circumstances.  What happens when versions change and separate projects you have want separate versions? But... that's just my opinion.

This would be a great thing to discuss in our slack room.  http://slack.actionherojs.com/

**Comment by evantahler** [comment]
Closing, because this isn't really about Yarn, but about global packages and overwriting things.
