### ISSUE TITLE
How deploy a web server and a worker on the same machine?

### ISSUE THREAD

**Issue by yinwz** [evantahler/actionhero#996]
I deploy a web server and a worker on the same machine using the same code.
Also, I modify the config files, turn off worker for server, and turn off server for work.
But, the server still do the tasks which should be done by worker.
Should I modify the serverToken and id for each roles?
Forgive my poor English!

**Comment by yinwz** [comment]
OS：win10_x64
Node.js：4.4.5
actionhero：16.0.0
redis：3.2.10(windows), default config

**Comment by yinwz** [comment]
I modify the id in config/api.js for each role, the result is still same.

**Comment by evantahler** [comment]
Common practice is to use environment variables to change the runtime behavior of your application. This lets you only need one copy of your code on your server, but you can boot the application in seperate modes. 

For example, in 'config/tasks.js' you could make minTaskProcessors and maxTaskProcessors equal to equivalent environment variables like 'process.env.MIN_TASK_PROCESSORS' and 'process.env.MAX_TASK_PROCESSORS'. Then you can book your application like this: 'MIN_TASK_PROCESSORS=1 MAX_TASK_PROCESSORS=5 ./node_modules/.bin/actionhero'. 

You can also set defaults to 0 and false to ensure that "a web server with no task processors" is the default behavior.

**Comment by yinwz** [comment]
I use environment variables 'ACTIONHERO_ROLE' to determin the runtime behavior, and change the queues in config/tasks.js for each role. Thus, it works well!

Follow your help, change  'MIN_TASK_PROCESSORS=0, MAX_TASK_PROCESSORS=0', no change quenes, also it works well.

Thank you!
